# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actionmailer-text` gem.
# Please instead update this file by running `bin/tapioca gem actionmailer-text`.


# source://actionmailer-text//lib/actionmailer-text/version.rb#1
module ActionMailer
  class << self
    # source://actionmailer/7.1.5/lib/action_mailer/deprecator.rb#4
    def deprecator; end

    # source://actionmailer/7.1.5/lib/action_mailer.rb#61
    def eager_load!; end

    # source://actionmailer/7.1.5/lib/action_mailer/gem_version.rb#5
    def gem_version; end

    # source://actionmailer/7.1.5/lib/action_mailer/version.rb#8
    def version; end
  end
end

# source://actionmailer-text//lib/actionmailer-text/version.rb#2
module ActionMailer::Text
  include ::ActionMailer::Text::HtmlToPlainText

  # source://actionmailer-text//lib/actionmailer-text/text.rb#9
  def collect_responses(headers); end

  class << self
    # @private
    #
    # source://actionmailer-text//lib/actionmailer-text/text.rb#3
    def included(klass); end
  end
end

# source://actionmailer-text//lib/actionmailer-text/html_to_plain_text.rb#12
module ActionMailer::Text::HtmlToPlainText
  # source://actionmailer-text//lib/actionmailer-text/html_to_plain_text.rb#13
  def convert_to_text(html, line_length = T.unsafe(nil), from_charset = T.unsafe(nil)); end

  class << self
    # Returns the text in UTF-8 format with all HTML tags removed
    #
    # TODO: add support for DL, OL
    #
    # source://actionmailer-text//lib/actionmailer-text/html_to_plain_text.rb#20
    def convert_to_text(html, line_length = T.unsafe(nil), _from_charset = T.unsafe(nil)); end

    # Taken from Rails' word_wrap helper (http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-word_wrap)
    #
    # source://actionmailer-text//lib/actionmailer-text/html_to_plain_text.rb#107
    def custom_word_wrap(txt, line_length); end
  end
end

# source://actionmailer-text//lib/actionmailer-text/version.rb#3
ActionMailer::Text::VERSION = T.let(T.unsafe(nil), String)
