# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `case_transform` gem.
# Please instead update this file by running `bin/tapioca gem case_transform`.


# source://case_transform//lib/case_transform/version.rb#2
module CaseTransform
  class << self
    # Transforms values to UpperCamelCase or PascalCase.
    #
    # @example:
    #    "some_key" => "SomeKey",
    #
    # source://case_transform//lib/case_transform.rb#29
    def camel(value); end

    # source://case_transform//lib/case_transform.rb#9
    def camel_cache; end

    # Transforms values to camelCase.
    #
    # @example:
    #    "some_key" => "someKey",
    #
    # source://case_transform//lib/case_transform.rb#43
    def camel_lower(value); end

    # source://case_transform//lib/case_transform.rb#13
    def camel_lower_cache; end

    # Transforms values to dashed-case.
    # This is the default case for the JsonApi adapter.
    #
    # @example:
    #    "some_key" => "some-key",
    #
    # source://case_transform//lib/case_transform.rb#58
    def dash(value); end

    # source://case_transform//lib/case_transform.rb#17
    def dash_cache; end

    # Returns the value unaltered
    #
    # source://case_transform//lib/case_transform.rb#84
    def unaltered(value); end

    # Transforms values to underscore_case.
    # This is the default case for deserialization in the JsonApi adapter.
    #
    # @example:
    #    "some-key" => "some_key",
    #
    # source://case_transform//lib/case_transform.rb#73
    def underscore(value); end

    # source://case_transform//lib/case_transform.rb#21
    def underscore_cache; end
  end
end

# source://case_transform//lib/case_transform/version.rb#3
CaseTransform::VERSION = T.let(T.unsafe(nil), String)
