# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `enum_help` gem.
# Please instead update this file by running `bin/tapioca gem enum_help`.


# source://enum_help//lib/enum_help/version.rb#1
module EnumHelp; end

# source://enum_help//lib/enum_help/i18n.rb#39
module EnumHelp::Helper
  class << self
    # source://enum_help//lib/enum_help/i18n.rb#41
    def define_attr_i18n_method(klass, attr_name); end

    # source://enum_help//lib/enum_help/i18n.rb#56
    def define_collection_i18n_method(klass, attr_name); end

    # source://enum_help//lib/enum_help/i18n.rb#70
    def translate_enum_label(klass, attr_name, enum_label); end
  end
end

# source://enum_help//lib/enum_help/i18n.rb#3
module EnumHelp::I18n
  # overwrite the enum method
  #
  # source://enum_help//lib/enum_help/i18n.rb#7
  def enum(name = T.unsafe(nil), values = T.unsafe(nil), **options); end

  class << self
    # @private
    #
    # source://enum_help//lib/enum_help/i18n.rb#31
    def extended(receiver); end
  end
end

# source://enum_help//lib/enum_help/railtie.rb#2
class EnumHelp::Railtie < ::Rails::Railtie; end

# source://enum_help//lib/enum_help/simple_form.rb#4
module EnumHelp::SimpleForm; end

# source://enum_help//lib/enum_help/simple_form.rb#5
module EnumHelp::SimpleForm::BuilderExtension
  # source://enum_help//lib/enum_help/simple_form.rb#7
  def default_input_type(*args, &block); end

  # @return [Boolean]
  #
  # source://enum_help//lib/enum_help/simple_form.rb#20
  def is_enum_attributes?(attribute_name); end
end

# source://enum_help//lib/enum_help/simple_form.rb#59
class EnumHelp::SimpleForm::EnumInput < ::SimpleForm::Inputs::CollectionSelectInput
  include ::EnumHelp::SimpleForm::InputExtension

  # source://enum_help//lib/enum_help/simple_form.rb#61
  def input_html_classes; end
end

# source://enum_help//lib/enum_help/simple_form.rb#67
class EnumHelp::SimpleForm::EnumRadioButtons < ::SimpleForm::Inputs::CollectionRadioButtonsInput
  include ::EnumHelp::SimpleForm::InputExtension
end

# source://enum_help//lib/enum_help/simple_form.rb#29
module EnumHelp::SimpleForm::InputExtension
  # source://enum_help//lib/enum_help/simple_form.rb#31
  def initialize(*args); end
end

# source://enum_help//lib/enum_help/version.rb#2
EnumHelp::VERSION = T.let(T.unsafe(nil), String)

class SimpleForm::FormBuilder < ::ActionView::Helpers::FormBuilder
  include ::EnumHelp::SimpleForm::BuilderExtension
end
