# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth_login_dot_gov` gem.
# Please instead update this file by running `bin/tapioca gem omniauth_login_dot_gov`.


# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#1
module OmniAuth
  class << self
    # source://omniauth/2.1.2/lib/omniauth.rb#134
    def config; end

    # source://omniauth/2.1.2/lib/omniauth.rb#138
    def configure; end

    # source://omniauth/2.1.2/lib/omniauth.rb#142
    def logger; end

    # source://omniauth/2.1.2/lib/omniauth.rb#146
    def mock_auth_for(provider); end

    # source://omniauth/2.1.2/lib/omniauth.rb#24
    def strategies; end
  end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#2
module OmniAuth::LoginDotGov; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#3
class OmniAuth::LoginDotGov::Authorization
  # @return [Authorization] a new instance of Authorization
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#7
  def initialize(session:, client:); end

  # Returns the value of attribute client.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#4
  def client; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#12
  def redirect_url; end

  # Returns the value of attribute session.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#4
  def session; end

  private

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#32
  def aal; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#53
  def acr_values; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#42
  def ial; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#89
  def nonce; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#20
  def redirect_url_params; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#79
  def state; end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/authorization.rb#5
OmniAuth::LoginDotGov::Authorization::VALID_AAL_VALUES = T.let(T.unsafe(nil), Array)

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#3
class OmniAuth::LoginDotGov::Callback
  # @return [Callback] a new instance of Callback
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#6
  def initialize(session:, client:); end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#11
  def call(params); end

  # Returns the value of attribute client.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#4
  def client; end

  # Returns the value of attribute id_token.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#4
  def id_token; end

  # Returns the value of attribute session.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#4
  def session; end

  # Returns the value of attribute userinfo.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#4
  def userinfo; end

  private

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#51
  def get_oidc_value_from_session(key); end

  # @raise [error_type]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#39
  def handle_error(params); end

  # @raise [CallbackStateMismatchError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/callback.rb#27
  def verify_state(params); end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#15
class OmniAuth::LoginDotGov::CallbackAccessDeniedError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#18
class OmniAuth::LoginDotGov::CallbackInvalidRequestError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#12
class OmniAuth::LoginDotGov::CallbackStateMismatchError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#3
class OmniAuth::LoginDotGov::Client
  # @return [Client] a new instance of Client
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#7
  def initialize(client_id:, ial:, idp_base_url:, private_key:, redirect_uri:, scope:, aal: T.unsafe(nil)); end

  # Returns the value of attribute aal.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def aal; end

  # Returns the value of attribute client_id.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def client_id; end

  # Returns the value of attribute ial.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def ial; end

  # Returns the value of attribute idp_configuration.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def idp_configuration; end

  # Returns the value of attribute private_key.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def private_key; end

  # Returns the value of attribute redirect_uri.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def redirect_uri; end

  # Returns the value of attribute scope.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/client.rb#4
  def scope; end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#3
class OmniAuth::LoginDotGov::Error < ::StandardError
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#4
  def key; end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token.rb#3
class OmniAuth::LoginDotGov::IdToken < ::Struct
  # @return [IdToken] a new instance of IdToken
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token.rb#10
  def initialize(client:, access_token:, id_token:, expires_in:, token_type:); end

  # Returns the value of attribute access_token
  #
  # @return [Object] the current value of access_token
  def access_token; end

  # Sets the attribute access_token
  #
  # @param value [Object] the value to set the attribute access_token to.
  # @return [Object] the newly set value
  def access_token=(_); end

  # Returns the value of attribute client
  #
  # @return [Object] the current value of client
  def client; end

  # Sets the attribute client
  #
  # @param value [Object] the value to set the attribute client to.
  # @return [Object] the newly set value
  def client=(_); end

  # Returns the value of attribute expires_in
  #
  # @return [Object] the current value of expires_in
  def expires_in; end

  # Sets the attribute expires_in
  #
  # @param value [Object] the value to set the attribute expires_in to.
  # @return [Object] the newly set value
  def expires_in=(_); end

  # Returns the value of attribute id_token
  #
  # @return [Object] the current value of id_token
  def id_token; end

  # Sets the attribute id_token
  #
  # @param value [Object] the value to set the attribute id_token to.
  # @return [Object] the newly set value
  def id_token=(_); end

  # Returns the value of attribute token_type
  #
  # @return [Object] the current value of token_type
  def token_type; end

  # Sets the attribute token_type
  #
  # @param value [Object] the value to set the attribute token_type to.
  # @return [Object] the newly set value
  def token_type=(_); end

  # @raise [IdTokenNonceMismatchError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token.rb#24
  def verify_nonce(session_nonce_digest); end

  private

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token.rb#36
  def decoded_id_token; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#24
class OmniAuth::LoginDotGov::IdTokenNonceMismatchError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#3
class OmniAuth::LoginDotGov::IdTokenRequest
  # @return [IdTokenRequest] a new instance of IdTokenRequest
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#6
  def initialize(code:, client:); end

  # Returns the value of attribute client.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#4
  def client; end

  # Returns the value of attribute code.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#4
  def code; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#11
  def request_id_token; end

  private

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#25
  def client_assertion_jwt; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#37
  def id_token_from_response(response); end

  # @raise [IdTokenRequestError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/id_token_request.rb#48
  def raise_id_token_request_failed_error(response); end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#21
class OmniAuth::LoginDotGov::IdTokenRequestError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#3
class OmniAuth::LoginDotGov::IdpConfiguration
  # @return [IdpConfiguration] a new instance of IdpConfiguration
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#4
  def initialize(idp_base_url:); end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#8
  def authorization_endpoint; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#20
  def end_session_endpoint; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#24
  def public_key; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#12
  def token_endpoint; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#16
  def userinfo_endpoint; end

  private

  # Returns the value of attribute idp_base_url.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#33
  def idp_base_url; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#56
  def jwks_endpoint_response; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#35
  def openid_configuration; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#39
  def openid_configuration_response; end

  # @raise [OpenidDiscoveryError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#64
  def raise_jwks_request_failed_error(response); end

  # @raise [OpenidDiscoveryError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/idp_configuration.rb#50
  def raise_openid_configuration_request_failed_error(response); end
end

# Assists in RP-initiated logout: https://developers.login.gov/oidc/#logout
#
# @example RP-initiated logout in Rails controller
#   class SessionsController < Devise::SessionsController
#   def destroy
#   logout_request = self.class.logout_utility.build_request(id_token: session[:id_token],
#   post_logout_redirect_uri: 'http://localhost:3001/'
#   )
#   sign_out(current_user)
#   redirect_to(logout_request.redirect_uri) and return
#   end
#
#   # Avoid making multiple HTTP requests to determine logout URL by memoizing utility class
#   def self.logout_utility
#   @logout_utility ||=
#   OmniAuth::LoginDotGov::LogoutUtility.new(idp_base_url: Rails.configuration.oidc['idp_url'])
#   end
#   end
#
# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#20
class OmniAuth::LoginDotGov::LogoutUtility
  # Initializes with one of idp_base_url, idp_configuration or end_session_endpoint.
  # Initializing with idp_base_url and idp_configuration may send an HTTP request to
  # fetch the OpenID configuration. The object should be memoized to avoid sending an
  # HTTP request for each logout.
  #
  # @return [LogoutUtility] a new instance of LogoutUtility
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#29
  def initialize(idp_base_url: T.unsafe(nil), idp_configuration: T.unsafe(nil), end_session_endpoint: T.unsafe(nil)); end

  # @param client_id [String]
  # @param post_logout_redirect_uri [String]
  # @param state [String]
  # @return [Request]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#52
  def build_request(client_id:, post_logout_redirect_uri:, state: T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#42
  def check_initialize_arguments!(idp_base_url, idp_configuration, end_session_endpoint); end

  # Returns the value of attribute state.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#21
  def state; end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/logout_utility.rb#23
class OmniAuth::LoginDotGov::LogoutUtility::Request < ::Struct
  # Returns the value of attribute redirect_uri
  #
  # @return [Object] the current value of redirect_uri
  def redirect_uri; end

  # Sets the attribute redirect_uri
  #
  # @param value [Object] the value to set the attribute redirect_uri to.
  # @return [Object] the newly set value
  def redirect_uri=(_); end

  # Returns the value of attribute state
  #
  # @return [Object] the current value of state
  def state; end

  # Sets the attribute state
  #
  # @param value [Object] the value to set the attribute state to.
  # @return [Object] the newly set value
  def state=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#9
class OmniAuth::LoginDotGov::OpenidDiscoveryError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/secure_compare.rb#3
class OmniAuth::LoginDotGov::SecureCompare
  class << self
    # Borrowed from Devise.secure_compare
    # Ref: https://github.com/plataformatec/devise/blob/cb663e96a370ba5d3dc6aa8ea3a2683268e980a0/lib/devise.rb#L500-L507
    #
    # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/secure_compare.rb#6
    def compare(a, b); end
  end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo.rb#3
class OmniAuth::LoginDotGov::Userinfo < ::Struct
  # @return [Userinfo] a new instance of Userinfo
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo.rb#17
  def initialize(uuid: T.unsafe(nil), email: T.unsafe(nil), email_verified: T.unsafe(nil), all_emails: T.unsafe(nil), family_name: T.unsafe(nil), given_name: T.unsafe(nil), birthdate: T.unsafe(nil), social_security_number: T.unsafe(nil), address: T.unsafe(nil), phone: T.unsafe(nil), phone_verified: T.unsafe(nil), verified_at: T.unsafe(nil)); end

  # Returns the value of attribute address
  #
  # @return [Object] the current value of address
  def address; end

  # Sets the attribute address
  #
  # @param value [Object] the value to set the attribute address to.
  # @return [Object] the newly set value
  def address=(_); end

  # Returns the value of attribute all_emails
  #
  # @return [Object] the current value of all_emails
  def all_emails; end

  # Sets the attribute all_emails
  #
  # @param value [Object] the value to set the attribute all_emails to.
  # @return [Object] the newly set value
  def all_emails=(_); end

  # Returns the value of attribute birthdate
  #
  # @return [Object] the current value of birthdate
  def birthdate; end

  # Sets the attribute birthdate
  #
  # @param value [Object] the value to set the attribute birthdate to.
  # @return [Object] the newly set value
  def birthdate=(_); end

  # Returns the value of attribute email
  #
  # @return [Object] the current value of email
  def email; end

  # Sets the attribute email
  #
  # @param value [Object] the value to set the attribute email to.
  # @return [Object] the newly set value
  def email=(_); end

  # Returns the value of attribute email_verified
  #
  # @return [Object] the current value of email_verified
  def email_verified; end

  # Sets the attribute email_verified
  #
  # @param value [Object] the value to set the attribute email_verified to.
  # @return [Object] the newly set value
  def email_verified=(_); end

  # Returns the value of attribute family_name
  #
  # @return [Object] the current value of family_name
  def family_name; end

  # Sets the attribute family_name
  #
  # @param value [Object] the value to set the attribute family_name to.
  # @return [Object] the newly set value
  def family_name=(_); end

  # Returns the value of attribute given_name
  #
  # @return [Object] the current value of given_name
  def given_name; end

  # Sets the attribute given_name
  #
  # @param value [Object] the value to set the attribute given_name to.
  # @return [Object] the newly set value
  def given_name=(_); end

  # Returns the value of attribute phone
  #
  # @return [Object] the current value of phone
  def phone; end

  # Sets the attribute phone
  #
  # @param value [Object] the value to set the attribute phone to.
  # @return [Object] the newly set value
  def phone=(_); end

  # Returns the value of attribute phone_verified
  #
  # @return [Object] the current value of phone_verified
  def phone_verified; end

  # Sets the attribute phone_verified
  #
  # @param value [Object] the value to set the attribute phone_verified to.
  # @return [Object] the newly set value
  def phone_verified=(_); end

  # Returns the value of attribute social_security_number
  #
  # @return [Object] the current value of social_security_number
  def social_security_number; end

  # Sets the attribute social_security_number
  #
  # @param value [Object] the value to set the attribute social_security_number to.
  # @return [Object] the newly set value
  def social_security_number=(_); end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo.rb#45
  def to_h; end

  # Returns the value of attribute uuid
  #
  # @return [Object] the current value of uuid
  def uuid; end

  # Sets the attribute uuid
  #
  # @param value [Object] the value to set the attribute uuid to.
  # @return [Object] the newly set value
  def uuid=(_); end

  # Returns the value of attribute verified_at
  #
  # @return [Object] the current value of verified_at
  def verified_at; end

  # Sets the attribute verified_at
  #
  # @param value [Object] the value to set the attribute verified_at to.
  # @return [Object] the newly set value
  def verified_at=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#3
class OmniAuth::LoginDotGov::UserinfoRequest
  # @return [UserinfoRequest] a new instance of UserinfoRequest
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#6
  def initialize(id_token:, client:); end

  # Returns the value of attribute client.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#4
  def client; end

  # Returns the value of attribute id_token.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#4
  def id_token; end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#11
  def request_userinfo; end

  private

  # @raise [UserinfoRequestError]
  #
  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#41
  def raise_userinfo_request_failed_error(response); end

  # source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/userinfo_request.rb#23
  def userinfo_from_response(response); end
end

# source://omniauth_login_dot_gov//lib/omniauth/login_dot_gov/errors.rb#27
class OmniAuth::LoginDotGov::UserinfoRequestError < ::OmniAuth::LoginDotGov::Error; end

# source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#2
module OmniAuth::Strategies; end

# source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#3
class OmniAuth::Strategies::LoginDotGov
  include ::OmniAuth::Strategy
  extend ::OmniAuth::Strategy::ClassMethods

  # Returns the value of attribute authorization.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#13
  def authorization; end

  # Returns the value of attribute callback.
  #
  # source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#13
  def callback; end

  # source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#36
  def callback_phase; end

  # source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#47
  def client; end

  # source://omniauth_login_dot_gov//lib/omniauth/strategies/login_dot_gov.rb#28
  def request_phase; end
end
