# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `secure_headers` gem.
# Please instead update this file by running `bin/tapioca gem secure_headers`.


# All headers (except for hpkp) have a default value. Provide SecureHeaders::OPT_OUT
# or ":optout_of_protection" as a config value to disable a given header
#
# source://secure_headers//lib/secure_headers/configuration.rb#3
module SecureHeaders
  # source://secure_headers//lib/secure_headers.rb#336
  def append_content_security_policy_directives(additions); end

  # source://secure_headers//lib/secure_headers.rb#324
  def content_security_policy_script_nonce; end

  # source://secure_headers//lib/secure_headers.rb#328
  def content_security_policy_style_nonce; end

  # source://secure_headers//lib/secure_headers.rb#332
  def opt_out_of_header(header_key); end

  # source://secure_headers//lib/secure_headers.rb#340
  def override_content_security_policy_directives(additions); end

  # source://secure_headers//lib/secure_headers.rb#344
  def override_x_frame_options(value); end

  # source://secure_headers//lib/secure_headers.rb#348
  def use_content_security_policy_named_append(name); end

  # These methods are mixed into controllers and delegate to the class method
  # with the same name.
  #
  # source://secure_headers//lib/secure_headers.rb#320
  def use_secure_headers_override(name); end

  class << self
    # Public: appends source values to the current configuration. If no value
    # is set for a given directive, the value will be merged with the default-src
    # value. If a value exists for the given directive, the values will be combined.
    #
    # additions - a hash containing directives. e.g.
    #    script_src: %w(another-host.com)
    #
    # source://secure_headers//lib/secure_headers.rb#114
    def append_content_security_policy_directives(request, additions, target = T.unsafe(nil)); end

    # Public: Retreives the config for a given header type:
    #
    # Checks to see if there is an override for this request, then
    # Checks to see if a named override is used for this request, then
    # Falls back to the global config
    #
    # source://secure_headers//lib/secure_headers.rb#228
    def config_for(request, prevent_dup = T.unsafe(nil)); end

    # Public: gets or creates a nonce for CSP.
    #
    # The nonce will be added to script_src
    #
    # Returns the nonce
    #
    # source://secure_headers//lib/secure_headers.rb#210
    def content_security_policy_script_nonce(request); end

    # Public: gets or creates a nonce for CSP.
    #
    # The nonce will be added to style_src
    #
    # Returns the nonce
    #
    # source://secure_headers//lib/secure_headers.rb#219
    def content_security_policy_style_nonce(request); end

    # Public: Builds the hash of headers that should be applied base on the
    # request.
    #
    # StrictTransportSecurity and PublicKeyPins are not applied to http requests.
    # See #config_for to determine which config is used for a given request.
    #
    # Returns a hash of header names => header values. The value
    # returned is meant to be merged into the header value from `@app.call(env)`
    # in Rack middleware.
    #
    # source://secure_headers//lib/secure_headers.rb#167
    def header_hash_for(request); end

    # Public: opts out of setting all headers by telling secure_headers to use
    # the NOOP configuration.
    #
    # source://secure_headers//lib/secure_headers.rb#154
    def opt_out_of_all_protection(request); end

    # Public: opts out of setting a given header by creating a temporary config
    # and setting the given headers config to OPT_OUT.
    #
    # source://secure_headers//lib/secure_headers.rb#146
    def opt_out_of_header(request, header_key); end

    # Public: override a given set of directives for the current request. If a
    # value already exists for a given directive, it will be overridden.
    #
    # If CSP was previously OPT_OUT, a new blank policy is used.
    #
    # additions - a hash containing directives. e.g.
    #    script_src: %w(another-host.com)
    #
    # source://secure_headers//lib/secure_headers.rb#86
    def override_content_security_policy_directives(request, additions, target = T.unsafe(nil)); end

    # Public: override X-Frame-Options settings for this request.
    #
    # value - deny, sameorigin, or allowall
    #
    # Returns the current config
    #
    # source://secure_headers//lib/secure_headers.rb#138
    def override_x_frame_options(request, value); end

    # source://secure_headers//lib/secure_headers.rb#128
    def use_content_security_policy_named_append(request, name); end

    # Public: specify which named override will be used for this request.
    # Raises an argument error if no named override exists.
    #
    # name - the name of the previously configured override.
    #
    # source://secure_headers//lib/secure_headers.rb#197
    def use_secure_headers_override(request, name); end

    private

    # source://secure_headers//lib/secure_headers.rb#251
    def config_and_target(request, target); end

    # Private: gets or creates a nonce for CSP.
    #
    # Returns the nonce
    #
    # source://secure_headers//lib/secure_headers.rb#273
    def content_security_policy_nonce(request, script_or_style); end

    # Private: chooses the applicable CSP header for the provided user agent.
    #
    # headers - a hash of header_config_key => [header_name, header_value]
    #
    # Returns a CSP [header, value] array
    #
    # source://secure_headers//lib/secure_headers.rb#313
    def csp_header_for_ua(headers, user_agent); end

    # source://secure_headers//lib/secure_headers.rb#258
    def guess_target(config); end

    # Private: determines which headers are applicable to a given request.
    #
    # Returns a list of classes whose corresponding header values are valid for
    # this request.
    #
    # source://secure_headers//lib/secure_headers.rb#292
    def header_classes_for(request); end

    # Private: convenience method for specifying which configuration object should
    # be used for this request.
    #
    # Returns the config.
    #
    # source://secure_headers//lib/secure_headers.rb#284
    def override_secure_headers_request_config(request, config); end

    # source://secure_headers//lib/secure_headers.rb#245
    def raise_on_unknown_target(target); end

    # source://secure_headers//lib/secure_headers.rb#300
    def update_cached_csp(config, headers, user_agent); end
  end
end

# source://secure_headers//lib/secure_headers.rb#69
SecureHeaders::ALL_HEADERS_BESIDES_CSP = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers.rb#54
SecureHeaders::ALL_HEADER_CLASSES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers.rb#52
SecureHeaders::CSP = SecureHeaders::ContentSecurityPolicy

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#3
class SecureHeaders::ClearSiteData
  class << self
    # Public: make an Clear-Site-Data header name, value pair
    #
    # Returns nil if not configured, returns header name and value if configured.
    #
    # source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#19
    def make_header(config = T.unsafe(nil)); end

    # Public: Transform a Clear-Site-Data config (an Array of Strings) into a
    # String that can be used as the value for the Clear-Site-Data header.
    #
    # types - An Array of String of types of data to clear.
    #
    # Returns a String of quoted values that are comma separated.
    #
    # source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#49
    def make_header_value(types); end

    # source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#30
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#11
SecureHeaders::ClearSiteData::ALL_TYPES = T.let(T.unsafe(nil), Array)

# Valid `types`
#
# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#7
SecureHeaders::ClearSiteData::CACHE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#13
SecureHeaders::ClearSiteData::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#8
SecureHeaders::ClearSiteData::COOKIES = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#10
SecureHeaders::ClearSiteData::EXECTION_CONTEXTS = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#4
SecureHeaders::ClearSiteData::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#9
SecureHeaders::ClearSiteData::STORAGE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/clear_site_data.rb#2
class SecureHeaders::ClearSiteDataConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/configuration.rb#4
class SecureHeaders::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#133
  def initialize(&block); end

  # Returns the value of attribute cached_headers.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def cached_headers; end

  # Sets the attribute clear_site_data
  #
  # @param value the value to set the attribute clear_site_data to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def clear_site_data=(_arg0); end

  # Returns the value of attribute cookies.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def cookies; end

  # Returns the value of attribute csp.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def csp; end

  # source://secure_headers//lib/secure_headers/configuration.rb#215
  def csp=(new_csp); end

  # Returns the value of attribute csp_report_only.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def csp_report_only; end

  # Configures the Content-Security-Policy-Report-Only header. `new_csp` cannot
  # contain `report_only: false` or an error will be raised.
  #
  # NOTE: if csp has not been configured/has the default value when
  # configuring csp_report_only, the code will assume you mean to only use
  # report-only mode and you will be opted-out of enforce mode.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#236
  def csp_report_only=(new_csp); end

  # Public: copy everything but the cached headers
  #
  # Returns a deep-dup'd copy of this configuration.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#159
  def dup; end

  # Sets the attribute expect_certificate_transparency
  #
  # @param value the value to set the attribute expect_certificate_transparency to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def expect_certificate_transparency=(_arg0); end

  # Returns the value of attribute hpkp.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def hpkp; end

  # Returns the value of attribute hpkp_report_host.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#121
  def hpkp_report_host; end

  # Sets the attribute hsts
  #
  # @param value the value to set the attribute hsts to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def hsts=(_arg0); end

  # source://secure_headers//lib/secure_headers/configuration.rb#179
  def opt_out(header); end

  # Sets the attribute referrer_policy
  #
  # @param value the value to set the attribute referrer_policy to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def referrer_policy=(_arg0); end

  # source://secure_headers//lib/secure_headers/configuration.rb#210
  def secure_cookies=(secure_cookies); end

  # source://secure_headers//lib/secure_headers/configuration.rb#184
  def update_x_frame_options(value); end

  # Public: validates all configurations values.
  #
  # Raises various configuration errors if any invalid config is detected.
  #
  # Returns nothing
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#194
  def validate_config!; end

  # Sets the attribute x_content_type_options
  #
  # @param value the value to set the attribute x_content_type_options to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def x_content_type_options=(_arg0); end

  # Sets the attribute x_download_options
  #
  # @param value the value to set the attribute x_download_options to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def x_download_options=(_arg0); end

  # Sets the attribute x_frame_options
  #
  # @param value the value to set the attribute x_frame_options to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def x_frame_options=(_arg0); end

  # Sets the attribute x_permitted_cross_domain_policies
  #
  # @param value the value to set the attribute x_permitted_cross_domain_policies to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def x_permitted_cross_domain_policies=(_arg0); end

  # Sets the attribute x_xss_protection
  #
  # @param value the value to set the attribute x_xss_protection to.
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#117
  def x_xss_protection=(_arg0); end

  protected

  # source://secure_headers//lib/secure_headers/configuration.rb#263
  def cached_headers=(headers); end

  # source://secure_headers//lib/secure_headers/configuration.rb#259
  def cookies=(cookies); end

  # source://secure_headers//lib/secure_headers/configuration.rb#267
  def hpkp=(hpkp); end

  # source://secure_headers//lib/secure_headers/configuration.rb#271
  def hpkp_report_host=(hpkp_report_host); end

  private

  # Public: Precompute the header names and values for this configuration.
  # Ensures that headers generated at configure time, not on demand.
  #
  # Returns the cached headers
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#289
  def cache_headers!; end

  # source://secure_headers//lib/secure_headers/configuration.rb#277
  def cache_hpkp_report_host; end

  # Private: adds CSP headers for each variation of CSP support.
  #
  # headers - generated headers are added to this hash namespaced by The
  #   different variations
  #
  # Returns nothing
  #
  # source://secure_headers//lib/secure_headers/configuration.rb#310
  def generate_csp_headers(headers); end

  # source://secure_headers//lib/secure_headers/configuration.rb#315
  def generate_csp_headers_for_config(headers, header_key, csp_config); end

  class << self
    # Public: Set the global default configuration.
    #
    # Optionally supply a block to override the defaults set by this library.
    #
    # Returns the newly created config.
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#15
    def configure(&block); end

    # Public: Set the global default configuration.
    #
    # Optionally supply a block to override the defaults set by this library.
    #
    # Returns the newly created config.
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#15
    def default(&block); end

    # Public: retrieve a global configuration object
    #
    # Returns the configuration with a given name or raises a
    # NotYetConfiguredError if `default` has not been called.
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#42
    def get(name = T.unsafe(nil)); end

    # source://secure_headers//lib/secure_headers/configuration.rb#54
    def named_append(name, target = T.unsafe(nil), &block); end

    # source://secure_headers//lib/secure_headers/configuration.rb#49
    def named_appends(name); end

    # Public: create a named configuration that overrides the default config.
    #
    # name - use an idenfier for the override config.
    # base - override another existing config, or override the default config
    # if no value is supplied.
    #
    # Returns: the newly created config
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#29
    def override(name, base = T.unsafe(nil), &block); end

    private

    # Private: add a valid configuration to the global set of named configs.
    #
    # config - the config to store
    # name - the lookup value for this config
    #
    # Raises errors if the config is invalid or if a config named `name`
    # already exists.
    #
    # Returns the config, if valid
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#71
    def add_configuration(name, config); end

    # Private: Automatically add an "opt-out of everything" override.
    #
    # Returns the noop config
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#83
    def add_noop_configuration; end

    # Public: perform a basic deep dup. The shallow copy provided by dup/clone
    # can lead to modifying parent objects.
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#95
    def deep_copy(config); end

    # Private: convenience method purely DRY things up. The value may not be a
    # hash (e.g. OPT_OUT, nil)
    #
    # source://secure_headers//lib/secure_headers/configuration.rb#108
    def deep_copy_if_hash(value); end
  end
end

# source://secure_headers//lib/secure_headers/configuration.rb#5
SecureHeaders::Configuration::DEFAULT_CONFIG = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/configuration.rb#126
SecureHeaders::Configuration::HASH_CONFIG_FILE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/configuration.rb#8
class SecureHeaders::Configuration::IllegalPolicyModificationError < ::StandardError; end

# source://secure_headers//lib/secure_headers/configuration.rb#6
SecureHeaders::Configuration::NOOP_CONFIGURATION = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/configuration.rb#7
class SecureHeaders::Configuration::NotYetConfiguredError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#6
class SecureHeaders::ContentSecurityPolicy
  include ::SecureHeaders::PolicyManagement
  extend ::SecureHeaders::PolicyManagement::ClassMethods

  # @return [ContentSecurityPolicy] a new instance of ContentSecurityPolicy
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#14
  def initialize(config = T.unsafe(nil), user_agent = T.unsafe(nil)); end

  # Returns the name to use for the header. Either "Content-Security-Policy" or
  # "Content-Security-Policy-Report-Only"
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#41
  def name; end

  # Return the value of the CSP header
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#47
  def value; end

  private

  # Private: adds a nonce or 'unsafe-inline' depending on browser support.
  # If a nonce is populated, inline content is assumed.
  #
  # While CSP is backward compatible in that a policy with a nonce will ignore
  # unsafe-inline, this is more concise.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#222
  def append_nonce(source_list, nonce); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#116
  def build_media_type_list_directive(directive); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#93
  def build_sandbox_list_directive(directive); end

  # Private: builds a string that represents one directive in a minified form.
  #
  # directive_name - a symbol representing the various ALL_DIRECTIVES
  #
  # Returns a string representing a directive.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#131
  def build_source_list_directive(directive); end

  # Private: converts the config object into a string representing a policy.
  # Places default-src at the first directive and report-uri as the last. All
  # others are presented in alphabetical order.
  #
  # Unsupported directives are filtered based on the user agent.
  #
  # Returns a content security policy header value.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#78
  def build_value; end

  # Removes duplicates and sources that already match an existing wild card.
  #
  # e.g. *.github.com asdf.github.com becomes *.github.com
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#190
  def dedup_source_list(sources); end

  # Private: return the list of directives that are supported by the user agent,
  # starting with default-src and ending with report-uri.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#236
  def directives; end

  # Discard trailing entries (excluding unsafe-*) since * accomplishes the same.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#174
  def keep_wildcard_sources(source_list); end

  # If a directive contains *, all other values are omitted.
  # If a directive contains 'none' but has other values, 'none' is ommitted.
  # Schemes are stripped (see http://www.w3.org/TR/CSP2/#match-source-expression)
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#158
  def minify_source_list(directive, source_list); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#268
  def nonces_supported?; end

  # frame-src is deprecated, child-src is being implemented. They are
  # very similar and in most cases, the same value can be used for both.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#59
  def normalize_child_frame_src; end

  # Private: append a nonce to the script/style directories if script_nonce
  # or style_nonce are provided.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#206
  def populate_nonces(directive, source_list); end

  # Discard any 'none' values if more directives are supplied since none may override values.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#179
  def reject_all_values_if_none(source_list); end

  # Private: Remove scheme from source expressions.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#245
  def strip_source_schemes(source_list); end

  # Private: determine which directives are supported for the given user agent.
  #
  # Add UA-sniffing special casing here.
  #
  # Returns an array of symbols representing the directives.
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#254
  def supported_directives; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#272
  def symbol_to_hyphen_case(sym); end
end

# source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#12
SecureHeaders::ContentSecurityPolicy::FALLBACK_VERSION = T.let(T.unsafe(nil), UserAgent::Version)

# source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#11
SecureHeaders::ContentSecurityPolicy::VERSION_10 = T.let(T.unsafe(nil), UserAgent::Version)

# constants to be used for version-specific UA sniffing
#
# source://secure_headers//lib/secure_headers/headers/content_security_policy.rb#10
SecureHeaders::ContentSecurityPolicy::VERSION_46 = T.let(T.unsafe(nil), UserAgent::Version)

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#120
class SecureHeaders::ContentSecurityPolicyConfig
  include ::SecureHeaders::DynamicConfig

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def base_uri; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def base_uri=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def block_all_mixed_content; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def block_all_mixed_content=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def child_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def child_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def connect_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def connect_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def default_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def default_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def font_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def font_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def form_action; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def form_action=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def frame_ancestors; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def frame_ancestors=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def frame_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def frame_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def img_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def img_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#145
  def make_report_only; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def manifest_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def manifest_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def media_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def media_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#4
  def modified=(_arg0); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def object_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def object_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def plugin_types; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def plugin_types=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def preserve_schemes; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def preserve_schemes=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def report_only; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def report_only=(value); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#141
  def report_only?; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def report_uri; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def report_uri=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def sandbox; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def sandbox=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def script_nonce; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def script_nonce=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def script_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def script_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def style_nonce; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def style_nonce=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def style_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def style_src=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def upgrade_insecure_requests; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def upgrade_insecure_requests=(value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#5
  def worker_src; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#7
  def worker_src=(value); end

  class << self
    # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#125
    def attrs; end
  end
end

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#124
SecureHeaders::ContentSecurityPolicyConfig::ATTRS = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#121
SecureHeaders::ContentSecurityPolicyConfig::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# based on what was suggested in https://github.com/rails/rails/pull/24961/files
#
# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#132
SecureHeaders::ContentSecurityPolicyConfig::DEFAULT = T.let(T.unsafe(nil), Hash)

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#122
SecureHeaders::ContentSecurityPolicyConfig::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#119
class SecureHeaders::ContentSecurityPolicyConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#150
class SecureHeaders::ContentSecurityPolicyReportOnlyConfig < ::SecureHeaders::ContentSecurityPolicyConfig
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#158
  def make_report_only; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#154
  def report_only?; end
end

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#151
SecureHeaders::ContentSecurityPolicyReportOnlyConfig::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#152
SecureHeaders::ContentSecurityPolicyReportOnlyConfig::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/cookie.rb#6
class SecureHeaders::Cookie
  # @return [Cookie] a new instance of Cookie
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#16
  def initialize(cookie, config); end

  # Returns the value of attribute config.
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#14
  def config; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#40
  def httponly?; end

  # Returns the value of attribute raw_cookie.
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#14
  def raw_cookie; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#44
  def samesite?; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#36
  def secure?; end

  # source://secure_headers//lib/secure_headers/headers/cookie.rb#28
  def to_s; end

  private

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#54
  def already_flagged?(attribute); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#69
  def conditionally_flag?(configuration); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#58
  def flag_cookie?(attribute); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#89
  def flag_samesite?; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#105
  def flag_samesite_enforcement?(mode); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#93
  def flag_samesite_lax?; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#101
  def flag_samesite_none?; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/cookie.rb#97
  def flag_samesite_strict?; end

  # source://secure_headers//lib/secure_headers/headers/cookie.rb#118
  def parse(cookie); end

  # source://secure_headers//lib/secure_headers/headers/cookie.rb#50
  def parsed_cookie; end

  # source://secure_headers//lib/secure_headers/headers/cookie.rb#79
  def samesite_cookie; end

  class << self
    # source://secure_headers//lib/secure_headers/headers/cookie.rb#9
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/utils/cookies_config.rb#2
class SecureHeaders::CookiesConfig
  # @return [CookiesConfig] a new instance of CookiesConfig
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#6
  def initialize(config); end

  # Returns the value of attribute config.
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#4
  def config; end

  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#10
  def validate!; end

  private

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#92
  def is_boolean?(obj); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#88
  def is_hash?(obj); end

  # @raise [CookiesConfigError]
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#21
  def validate_config!; end

  # validate exclusive use of only or except but not both at the same time
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#73
  def validate_exclusive_use_of_hash_constraints!(conf, attribute); end

  # validate exclusivity of only and except members within strict and lax
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#82
  def validate_exclusive_use_of_samesite_enforcement!(attribute); end

  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#66
  def validate_hash_or_boolean!(attribute); end

  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#30
  def validate_httponly_config!; end

  # when configuring with booleans, only one enforcement is permitted
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#43
  def validate_samesite_boolean_config!; end

  # @raise [CookiesConfigError]
  #
  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#35
  def validate_samesite_config!; end

  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#53
  def validate_samesite_hash_config!; end

  # source://secure_headers//lib/secure_headers/utils/cookies_config.rb#25
  def validate_secure_config!; end
end

# source://secure_headers//lib/secure_headers/headers/cookie.rb#5
class SecureHeaders::CookiesConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#2
module SecureHeaders::DynamicConfig
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#17
  def initialize(hash); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#88
  def ==(o); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#51
  def [](directive); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#47
  def []=(directive, value); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#69
  def append(new_hash); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#51
  def directive_value(directive); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#80
  def dup; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#61
  def merge(new_hash); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#65
  def merge!(new_hash); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#57
  def modified?; end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#84
  def opt_out?; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#73
  def to_h; end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#47
  def update_directive(directive, value); end

  private

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#96
  def from_hash(hash); end

  # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#108
  def write_attribute(attr, value); end

  class << self
    # @private
    #
    # source://secure_headers//lib/secure_headers/headers/content_security_policy_config.rb#3
    def included(base); end
  end
end

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#5
class SecureHeaders::ExpectCertificateTransparency
  # @return [ExpectCertificateTransparency] a new instance of ExpectCertificateTransparency
  #
  # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#41
  def initialize(config); end

  # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#55
  def enforced_directive; end

  # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#62
  def max_age_directive; end

  # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#66
  def report_uri_directive; end

  # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#47
  def value; end

  class << self
    # Public: Generate a Expect-CT header.
    #
    # Returns nil if not configured, returns header name and value if
    # configured.
    #
    # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#18
    def make_header(config); end

    # @raise [ExpectCertificateTransparencyConfigError]
    #
    # source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#25
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#7
SecureHeaders::ExpectCertificateTransparency::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#6
SecureHeaders::ExpectCertificateTransparency::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#8
SecureHeaders::ExpectCertificateTransparency::INVALID_CONFIGURATION_ERROR = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#9
SecureHeaders::ExpectCertificateTransparency::INVALID_ENFORCE_VALUE_ERROR = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#11
SecureHeaders::ExpectCertificateTransparency::INVALID_MAX_AGE_ERROR = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#10
SecureHeaders::ExpectCertificateTransparency::REQUIRED_MAX_AGE_ERROR = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/expect_certificate_transparency.rb#3
class SecureHeaders::ExpectCertificateTransparencyConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers.rb#51
SecureHeaders::HTTPS = T.let(T.unsafe(nil), String)

# Headers set on http requests (excludes STS and HPKP)
#
# source://secure_headers//lib/secure_headers.rb#75
SecureHeaders::HTTP_HEADER_CLASSES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/hash_helper.rb#4
module SecureHeaders::HashHelper
  # source://secure_headers//lib/secure_headers/hash_helper.rb#5
  def hash_source(inline_script, digest = T.unsafe(nil)); end
end

# source://secure_headers//lib/secure_headers/middleware.rb#2
class SecureHeaders::Middleware
  # @return [Middleware] a new instance of Middleware
  #
  # source://secure_headers//lib/secure_headers/middleware.rb#5
  def initialize(app); end

  # merges the hash of headers into the current header set.
  #
  # source://secure_headers//lib/secure_headers/middleware.rb#10
  def call(env); end

  private

  # inspired by https://github.com/tobmatth/rack-ssl-enforcer/blob/6c014/lib/rack/ssl-enforcer.rb#L183-L194
  #
  # source://secure_headers//lib/secure_headers/middleware.rb#27
  def flag_cookies!(headers, config); end

  # disable Secure cookies for non-https requests
  #
  # source://secure_headers//lib/secure_headers/middleware.rb#39
  def override_secure(env, config = T.unsafe(nil)); end

  # derived from https://github.com/tobmatth/rack-ssl-enforcer/blob/6c014/lib/rack/ssl-enforcer.rb#L119
  #
  # source://secure_headers//lib/secure_headers/middleware.rb#48
  def scheme(env); end
end

# source://secure_headers//lib/secure_headers/middleware.rb#3
SecureHeaders::Middleware::HPKP_SAME_HOST_WARNING = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers.rb#50
SecureHeaders::NONCE_KEY = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers.rb#24
class SecureHeaders::NoOpHeaderConfig
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # source://secure_headers//lib/secure_headers.rb#27
  def [](arg = T.unsafe(nil)); end

  # source://secure_headers//lib/secure_headers.rb#27
  def []=(arg = T.unsafe(nil)); end

  # source://secure_headers//lib/secure_headers.rb#27
  def boom(arg = T.unsafe(nil)); end

  # source://secure_headers//lib/secure_headers.rb#35
  def dup; end

  # source://secure_headers//lib/secure_headers.rb#27
  def keys(arg = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers.rb#39
  def opt_out?; end

  # source://secure_headers//lib/secure_headers.rb#31
  def to_h; end

  class << self
    private

    def allocate; end
    def new(*_arg0); end
  end
end

# source://secure_headers//lib/secure_headers.rb#48
SecureHeaders::OPT_OUT = T.let(T.unsafe(nil), SecureHeaders::NoOpHeaderConfig)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#2
module SecureHeaders::PolicyManagement
  mixes_in_class_methods ::SecureHeaders::PolicyManagement::ClassMethods

  class << self
    # @private
    #
    # source://secure_headers//lib/secure_headers/headers/policy_management.rb#3
    def included(base); end
  end
end

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#111
SecureHeaders::PolicyManagement::ALL_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#48
SecureHeaders::PolicyManagement::BASE_URI = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#11
SecureHeaders::PolicyManagement::BLOB_PROTOCOL = T.let(T.unsafe(nil), String)

# All the directives currently under consideration for CSP level 3.
# https://w3c.github.io/webappsec/specs/CSP2/
#
# source://secure_headers//lib/secure_headers/headers/policy_management.rb#65
SecureHeaders::PolicyManagement::BLOCK_ALL_MIXED_CONTENT = T.let(T.unsafe(nil), Symbol)

# Think of default-src and report-uri as the beginning and end respectively,
# everything else is in between.
#
# source://secure_headers//lib/secure_headers/headers/policy_management.rb#115
SecureHeaders::PolicyManagement::BODY_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#49
SecureHeaders::PolicyManagement::CHILD_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#107
SecureHeaders::PolicyManagement::CHROME_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#23
SecureHeaders::PolicyManagement::CONNECT_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#191
module SecureHeaders::PolicyManagement::ClassMethods
  # Public: combine the values from two different configs.
  #
  # original - the main config
  # additions - values to be merged in
  #
  # raises an error if the original config is OPT_OUT
  #
  # 1. for non-source-list values (report_only, block_all_mixed_content, upgrade_insecure_requests),
  # additions will overwrite the original value.
  # 2. if a value in additions does not exist in the original config, the
  # default-src value is included to match original behavior.
  # 3. if a value in additions does exist in the original config, the two
  # values are joined.
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#241
  def combine_policies(original, additions); end

  # Public: generate a header name, value array that is user-agent-aware.
  #
  # Returns a default policy if no configuration is provided, or a
  # header name and value based on the config.
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#196
  def make_header(config, user_agent); end

  # Public: check if a user agent supports CSP nonces
  #
  # user_agent - a String or a UserAgent object
  #
  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#222
  def nonces_supported?(user_agent); end

  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#251
  def ua_to_variation(user_agent); end

  # Public: Validates each source expression.
  #
  # Does not validate the invididual values of the source expression (e.g.
  # script_src => h*t*t*p: will not raise an exception)
  #
  # @raise [ContentSecurityPolicyConfigError]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#205
  def validate_config!(config); end

  private

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#399
  def boolean?(source_expression); end

  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#299
  def default_for(directive, original); end

  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#385
  def ensure_array_of_strings!(directive, value); end

  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#379
  def ensure_valid_directive!(directive); end

  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#391
  def ensure_valid_sources!(directive, source_expression); end

  # Returns True if a directive expects a list of values and False otherwise.
  #
  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#275
  def list_directive?(directive); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#313
  def media_type_list?(directive); end

  # merge the two hashes. combine (instead of overwrite) the array values
  # when each hash contains a value for a given key.
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#264
  def merge_policy_additions(original, additions); end

  # For each directive in additions that does not exist in the original config,
  # copy the default-src value to the original config. This modifies the original hash.
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#283
  def populate_fetch_source_with_default!(original, additions); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#309
  def sandbox_list?(directive); end

  # @return [Boolean]
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#305
  def source_list?(directive); end

  # Private: Validates that the configuration has a valid type, or that it is a valid
  # source expression.
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#319
  def validate_directive!(directive, value); end

  # Private: validates that a media type expression:
  # 1. is an array of strings
  # 2. each element is of the form type/subtype
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#355
  def validate_media_type_expression!(directive, media_type_expression); end

  # Private: validates that a sandbox token expression:
  # 1. is an array of strings or optionally `true` (to enable maximal sandboxing)
  # 2. For arrays, each element is of the form allow-*
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#340
  def validate_sandbox_expression!(directive, sandbox_token_expression); end

  # Private: validates that a source expression:
  # 1. is an array of strings
  # 2. does not contain any deprecated, now invalid values (inline, eval, self, none)
  #
  # Does not validate the invididual values of the source expression (e.g.
  # script_src => h*t*t*p: will not raise an exception)
  #
  # source://secure_headers//lib/secure_headers/headers/policy_management.rb#372
  def validate_source_expression!(directive, source_expression); end
end

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#10
SecureHeaders::PolicyManagement::DATA_PROTOCOL = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#9
SecureHeaders::PolicyManagement::DEFAULT_CONFIG = T.let(T.unsafe(nil), Hash)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#22
SecureHeaders::PolicyManagement::DEFAULT_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#8
SecureHeaders::PolicyManagement::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# leftover deprecated values that will be in common use upon upgrading.
#
# source://secure_headers//lib/secure_headers/headers/policy_management.rb#20
SecureHeaders::PolicyManagement::DEPRECATED_SOURCE_VALUES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#34
SecureHeaders::PolicyManagement::DIRECTIVES_1_0 = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#54
SecureHeaders::PolicyManagement::DIRECTIVES_2_0 = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#70
SecureHeaders::PolicyManagement::DIRECTIVES_3_0 = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#130
SecureHeaders::PolicyManagement::DIRECTIVE_VALUE_TYPES = T.let(T.unsafe(nil), Hash)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#78
SecureHeaders::PolicyManagement::EDGE_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#168
SecureHeaders::PolicyManagement::FETCH_SOURCES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#89
SecureHeaders::PolicyManagement::FIREFOX_46_DEPRECATED_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#103
SecureHeaders::PolicyManagement::FIREFOX_46_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#93
SecureHeaders::PolicyManagement::FIREFOX_46_UNSUPPORTED_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#99
SecureHeaders::PolicyManagement::FIREFOX_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#82
SecureHeaders::PolicyManagement::FIREFOX_UNSUPPORTED_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#24
SecureHeaders::PolicyManagement::FONT_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#50
SecureHeaders::PolicyManagement::FORM_ACTION = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#51
SecureHeaders::PolicyManagement::FRAME_ANCESTORS = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#25
SecureHeaders::PolicyManagement::FRAME_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#171
SecureHeaders::PolicyManagement::HTTP_SCHEME_REGEX = T.let(T.unsafe(nil), Regexp)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#26
SecureHeaders::PolicyManagement::IMG_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#66
SecureHeaders::PolicyManagement::MANIFEST_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#27
SecureHeaders::PolicyManagement::MEDIA_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#181
SecureHeaders::PolicyManagement::META_CONFIGS = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#7
SecureHeaders::PolicyManagement::MODERN_BROWSERS = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#186
SecureHeaders::PolicyManagement::NONCES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#13
SecureHeaders::PolicyManagement::NONE = T.let(T.unsafe(nil), String)

# These are directives that take a source list, but that do not inherit
# the default-src value.
#
# source://secure_headers//lib/secure_headers/headers/policy_management.rb#161
SecureHeaders::PolicyManagement::NON_FETCH_SOURCES = T.let(T.unsafe(nil), Array)

# These are directives that don't have use a source list, and hence do not
# inherit the default-src value.
#
# source://secure_headers//lib/secure_headers/headers/policy_management.rb#155
SecureHeaders::PolicyManagement::NON_SOURCE_LIST_SOURCES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#28
SecureHeaders::PolicyManagement::OBJECT_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#128
SecureHeaders::PolicyManagement::OTHER = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#52
SecureHeaders::PolicyManagement::PLUGIN_TYPES = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#32
SecureHeaders::PolicyManagement::REPORT_URI = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#80
SecureHeaders::PolicyManagement::SAFARI_10_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#79
SecureHeaders::PolicyManagement::SAFARI_DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#29
SecureHeaders::PolicyManagement::SANDBOX = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#30
SecureHeaders::PolicyManagement::SCRIPT_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#12
SecureHeaders::PolicyManagement::SELF = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#14
SecureHeaders::PolicyManagement::STAR = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#170
SecureHeaders::PolicyManagement::STAR_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#17
SecureHeaders::PolicyManagement::STRICT_DYNAMIC = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#31
SecureHeaders::PolicyManagement::STYLE_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#16
SecureHeaders::PolicyManagement::UNSAFE_EVAL = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#15
SecureHeaders::PolicyManagement::UNSAFE_INLINE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#67
SecureHeaders::PolicyManagement::UPGRADE_INSECURE_REQUESTS = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#117
SecureHeaders::PolicyManagement::VARIATIONS = T.let(T.unsafe(nil), Hash)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#173
SecureHeaders::PolicyManagement::WILDCARD_SOURCES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/policy_management.rb#68
SecureHeaders::PolicyManagement::WORKER_SRC = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#3
class SecureHeaders::PublicKeyPins
  # @return [PublicKeyPins] a new instance of PublicKeyPins
  #
  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#35
  def initialize(config); end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#69
  def max_age_directive; end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#43
  def name; end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#60
  def pin_directives; end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#73
  def report_uri_directive; end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#77
  def subdomain_directive; end

  # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#51
  def value; end

  class << self
    # Public: make an hpkp header name, value pair
    #
    # Returns nil if not configured, returns header name and value if configured.
    #
    # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#14
    def make_header(config); end

    # @raise [PublicKeyPinsConfigError]
    #
    # source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#20
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#7
SecureHeaders::PublicKeyPins::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#6
SecureHeaders::PublicKeyPins::HASH_ALGORITHMS = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#4
SecureHeaders::PublicKeyPins::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#5
SecureHeaders::PublicKeyPins::REPORT_ONLY = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/public_key_pins.rb#2
class SecureHeaders::PublicKeyPinsConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/railtie.rb#4
class SecureHeaders::Railtie < ::Rails::Railtie; end

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#3
class SecureHeaders::ReferrerPolicy
  class << self
    # Public: generate an Referrer Policy header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#23
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#27
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#16
SecureHeaders::ReferrerPolicy::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#5
SecureHeaders::ReferrerPolicy::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#4
SecureHeaders::ReferrerPolicy::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#6
SecureHeaders::ReferrerPolicy::VALID_POLICIES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/referrer_policy.rb#2
class SecureHeaders::ReferrerPolicyConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers.rb#49
SecureHeaders::SECURE_HEADERS_CONFIG = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#2
class SecureHeaders::STSConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#4
class SecureHeaders::StrictTransportSecurity
  class << self
    # Public: generate an hsts header name, value pair.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#17
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#21
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#10
SecureHeaders::StrictTransportSecurity::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#7
SecureHeaders::StrictTransportSecurity::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#5
SecureHeaders::StrictTransportSecurity::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#6
SecureHeaders::StrictTransportSecurity::HSTS_MAX_AGE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#9
SecureHeaders::StrictTransportSecurity::MESSAGE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/strict_transport_security.rb#8
SecureHeaders::StrictTransportSecurity::VALID_STS_HEADER = T.let(T.unsafe(nil), Regexp)

# source://secure_headers//lib/secure_headers/view_helper.rb#2
module SecureHeaders::ViewHelpers
  include ::SecureHeaders::HashHelper

  # Public: use the content security policy nonce for this request directly.
  # Instructs secure_headers to append a nonce to style/script-src directives.
  #
  # Returns a non-html-safe nonce value.
  #
  # source://secure_headers//lib/secure_headers/view_helper.rb#28
  def content_security_policy_nonce(type); end

  # source://secure_headers//lib/secure_headers/view_helper.rb#37
  def content_security_policy_script_nonce; end

  # source://secure_headers//lib/secure_headers/view_helper.rb#41
  def content_security_policy_style_nonce; end

  # Checks to see if the hashed code is expected and adds the hash source
  # value to the current CSP.
  #
  # By default, in development/test/etc. an exception will be raised.
  #
  # source://secure_headers//lib/secure_headers/view_helper.rb#50
  def hashed_javascript_tag(raise_error_on_unrecognized_hash = T.unsafe(nil), &block); end

  # source://secure_headers//lib/secure_headers/view_helper.rb#60
  def hashed_style_tag(raise_error_on_unrecognized_hash = T.unsafe(nil), &block); end

  # Public: create a script tag using the content security policy nonce.
  # Instructs secure_headers to append a nonce to style/script-src directives.
  #
  # Returns an html-safe script tag with the nonce attribute.
  #
  # source://secure_headers//lib/secure_headers/view_helper.rb#20
  def nonced_javascript_tag(content_or_options = T.unsafe(nil), &block); end

  # Public: create a style tag using the content security policy nonce.
  # Instructs secure_headers to append a nonce to style/script-src directives.
  #
  # Returns an html-safe style tag with the nonce attribute.
  #
  # source://secure_headers//lib/secure_headers/view_helper.rb#12
  def nonced_style_tag(content_or_options = T.unsafe(nil), &block); end

  private

  # source://secure_headers//lib/secure_headers/view_helper.rb#72
  def hashed_tag(type, directive, hashes, raise_error_on_unrecognized_hash, block); end

  # source://secure_headers//lib/secure_headers/view_helper.rb#106
  def nonced_tag(type, content_or_options, block); end

  # source://secure_headers//lib/secure_headers/view_helper.rb#94
  def unexpected_hash_error_message(file_path, content, hash_value); end
end

# source://secure_headers//lib/secure_headers/view_helper.rb#4
SecureHeaders::ViewHelpers::SECURE_HEADERS_RAKE_TASK = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/view_helper.rb#6
class SecureHeaders::ViewHelpers::UnexpectedHashedScriptException < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#4
class SecureHeaders::XContentTypeOptions
  class << self
    # Public: generate an X-Content-Type-Options header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#14
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#18
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#7
SecureHeaders::XContentTypeOptions::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#6
SecureHeaders::XContentTypeOptions::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#5
SecureHeaders::XContentTypeOptions::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_content_type_options.rb#2
class SecureHeaders::XContentTypeOptionsConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/x_download_options.rb#2
class SecureHeaders::XDOConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/x_download_options.rb#3
class SecureHeaders::XDownloadOptions
  class << self
    # Public: generate an X-Download-Options header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/x_download_options.rb#13
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/x_download_options.rb#17
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/x_download_options.rb#6
SecureHeaders::XDownloadOptions::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/x_download_options.rb#5
SecureHeaders::XDownloadOptions::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_download_options.rb#4
SecureHeaders::XDownloadOptions::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#2
class SecureHeaders::XFOConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#3
class SecureHeaders::XFrameOptions
  class << self
    # Public: generate an X-Frame-Options header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#18
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#23
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#9
SecureHeaders::XFrameOptions::ALLOW_ALL = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#8
SecureHeaders::XFrameOptions::ALLOW_FROM = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#5
SecureHeaders::XFrameOptions::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#10
SecureHeaders::XFrameOptions::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#7
SecureHeaders::XFrameOptions::DENY = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#4
SecureHeaders::XFrameOptions::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#6
SecureHeaders::XFrameOptions::SAMEORIGIN = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_frame_options.rb#11
SecureHeaders::XFrameOptions::VALID_XFO_HEADER = T.let(T.unsafe(nil), Regexp)

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#2
class SecureHeaders::XPCDPConfigError < ::StandardError; end

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#3
class SecureHeaders::XPermittedCrossDomainPolicies
  class << self
    # Public: generate an X-Permitted-Cross-Domain-Policies header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#14
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#18
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#7
SecureHeaders::XPermittedCrossDomainPolicies::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#5
SecureHeaders::XPermittedCrossDomainPolicies::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#4
SecureHeaders::XPermittedCrossDomainPolicies::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_permitted_cross_domain_policies.rb#6
SecureHeaders::XPermittedCrossDomainPolicies::VALID_POLICIES = T.let(T.unsafe(nil), Array)

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#3
class SecureHeaders::XXssProtection
  class << self
    # Public: generate an X-Xss-Protection header.
    #
    # Returns a default header if no configuration is provided, or a
    # header name and value based on the config.
    #
    # source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#14
    def make_header(config = T.unsafe(nil)); end

    # @raise [TypeError]
    #
    # source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#18
    def validate_config!(config); end
  end
end

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#7
SecureHeaders::XXssProtection::CONFIG_KEY = T.let(T.unsafe(nil), Symbol)

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#5
SecureHeaders::XXssProtection::DEFAULT_VALUE = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#4
SecureHeaders::XXssProtection::HEADER_NAME = T.let(T.unsafe(nil), String)

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#6
SecureHeaders::XXssProtection::VALID_X_XSS_HEADER = T.let(T.unsafe(nil), Regexp)

# source://secure_headers//lib/secure_headers/headers/x_xss_protection.rb#2
class SecureHeaders::XXssProtectionConfigError < ::StandardError; end
