# This expects a file name that contains the output generated by
# the rake extracts:import script (Array of ServiceProviders JSON)
class ServiceProviderArchiver
  extend ActiveModel::Naming
  # :issuer needs to be present for error handling
  attr_reader :file_name, :data, :models, :issuer
  attr_accessor :dry_run

  def initialize(file_name)
    @file_name = file_name
    @models = []
  end

  def run
    validate_file unless data
    return errors if errors_any?

    archive unless dry_run
    errors
  end

  # This is required to treat this class as a model for purposes of
  # generating errors.
  def read_attribute_for_validation(attr)
    send(attr)
  end

  # This is also required for errors. See
  # https://api.rubyonrails.org/classes/ActiveModel/Errors.html#class-ActiveModel::Errors-label-Active+Model+Errors
  def self.human_attribute_name(attr, _options = {})
    attr
  end

  def errors_any?
    errors.values.any?
  end

  private

  def validate_file
    raise ArgumentError, "File #{file_name} cannot be opened" unless File.readable?(file_name)

    File.open(file_name) do |file|
      @data = JSON.parse(file.read)['service_providers']
    end
  end

  def sp_issuers
    @issuers ||= data.map { |config| config['issuer'] }
  end

  def errors
    @errors ||= sp_issuers.each_with_object({}) do |issuer, error_list|
      model = ServiceProvider.find_by(issuer: issuer)
      if model.blank?
        model_errors = ActiveModel::Errors.new(self)
        model_errors.add(:issuer, :invalid, message: "#{issuer} not found")
        error_list[issuer] = model_errors
      else
        models.push(model)
      end
    end
  end

  def archive
    models.each do |model|
      model.status = 'moved_to_prod'
      model.save
    end
  end
end
