# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Wicked::Wizard::Translated`.
# Please instead update this file by running `bin/tapioca dsl Wicked::Wizard::Translated`.


module Wicked::Wizard::Translated
  mixes_in_class_methods ::Wicked::Controller::Concerns::Steps::ClassMethods
end
