engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
        # mass_threshold: 30
      - javascript
    exclude_paths:
    - 'spec/**/*'
  fixme:
    enabled: false
  rubocop:
    enabled: false

ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
