version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 5
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 50
    exclude_patterns:
    - 'spec/**/*'
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
      - HACK
      - BUG
      - XXX
  pep8:
    enabled: true
  reek:
    enabled: true
    exclude_patterns:
    - 'spec/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'app/forms/password_form.rb'
    - 'lib/user_flow_exporter.rb'
    - 'lib/rspec/formatters/user_flow_formatter.rb'
  rubocop:
    enabled: true
    channel: rubocop-0-54
  scss-lint:
    enabled: true

exclude_patterns:
  - 'public/'
  - 'spec/'
  - 'db/'
