version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 6
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    exclude_fingerprints:
      # omniauth CVE-2015-9284
    - 66ed39bb85e54152ee5e2343f95f4b53
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 50
    exclude_patterns:
    - 'spec/**/*'
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
      - HACK
      - BUG
      - XXX
  pep8:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
  - 'public/'
  - 'spec/'
  - 'db/'
  - 'app/models/service_provider.rb'
  - 'app/services/service_provider_logo_updater.rb'
