detectors:
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    exclude:
      - FakeSamlIdp#build_configs
  UtilityFunction:
    public_methods_only: true
    exclude:
      - TeamHelper#can_edit_teams?
  NilCheck:
    exclude:
      - TeamPolicy#admin?

exclude_paths:
  - db/migrate
  - spec
