inherit_from: .rubocop_todo.yml

# This configuration only includes the cops that differ from the Rubocop
# defaults, which can be found here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
# https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance

inherit_gem:
  pundit: config/rubocop-rspec.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/i18n_spec.rb'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/deploy.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/devise.rb'
    - 'config/puma.rb'
    - 'db/migrate/*'
    - '**/Capfile'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: <%= File.read(File.join(__dir__, '.ruby-version')).strip %>
  TargetRailsVersion: 7.2
  UseCache: true
  NewCops: enable
  DisabledByDefault: false
  SuggestExtensions: true

Capybara/NegationMatcher:
  EnforcedStyle: not_to

Capybara/SpecificFinders:
  Enabled: false

Capybara/SpecificMatcher:
  Enabled: false

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Enabled: true
  Max: 25
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'


Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  IndentationWidth: null

# Layout/DefEndAlignment:
#   Enabled: true
#   AutoCorrect: true
#   Severity: warning

# Layout/DotPosition:
  # EnforcedStyle: leading
#   Enabled: false

Layout/EmptyComment:
  Enabled: true
  AllowBorderComment: true
  AllowMarginComment: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Lint/MissingSuper:
  # ViewComponent::Base and BasePolicy have no meaningful base class initializers 
  # that we'd want to call `super` on.
  Exclude:
   - app/policies/**/*.rb
   - app/components/**/*.rb

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

# Layout/ExtraSpacing:
#   # When true, allows most uses of extra spacing if the intent is to align
#   # things with the previous or next line, not counting empty lines or comment
#   # lines.
#   AllowForAlignment: true
#   # When true, forces the alignment of = in assignments on consecutive lines.
#   ForceEqualSignAlignment: false

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

# Checks the indentation of the first element in an array literal.
Layout/FirstArrayElementIndentation:
  # The value `special_inside_parentheses` means that array literals with
  # brackets that have their opening bracket on the same line as a surrounding
  # opening round parenthesis, shall have their first element indented relative
  # to the first position inside the parenthesis.
  #
  # The value `consistent` means that the indentation of the first element shall
  # always be relative to the first position of the line where the opening
  # bracket is.
  #
  # The value `align_brackets` means that the indentation of the first element
  # shall always be relative to the position of the opening bracket.
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_brackets
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: ~

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Description: Limit lines to 100 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https
  Exclude:
    - 'config/routes.rb'
  
Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

# Layout/MultilineHashBraceLayout:
#   Enabled: true
#   EnforcedStyle: symmetrical

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
  
# Layout/MultilineOperationIndentation:
#   EnforcedStyle: aligned
#   SupportedStyles:
#     - aligned
#     - indented
#   # By default, the indentation width from Style/IndentationWidth is used
#   # But it can be overridden by setting this parameter
#   IndentationWidth: ~

# Layout/ParameterAlignment:
#   # Alignment of parameters in multi-line method calls.
#   #
#   # The `with_first_parameter` style aligns the following lines along the same
#   # column as the first parameter.
#   #
#   #     method_call(a,
#   #                 b)
#   #
#   # The `with_fixed_indentation` style aligns the following lines with one
#   # level of indentation relative to the start of the line with the method call.
#   #
#   #     method_call(a,
#   #       b)
#   Description: >-
#                  Align the parameters of a method call if they span more
#                  than one line.
#   StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-double-indent'
#   EnforcedStyle: with_first_parameter
#   SupportedStyles:
#     - with_first_parameter
#     - with_fixed_indentation
#   # By default, the indentation width from Style/IndentationWidth is used
#   # But it can be overridden by setting this parameter
#   IndentationWidth: ~

# Layout/SpaceAroundBlockParameters:
#   Enabled: true
#   EnforcedStyleInsidePipes: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space

# Layout/SpaceAroundOperators:
#   Enabled: true
#   EnforcedStyleForExponentOperator: space
#   AllowForAlignment: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

# Layout/SpaceBeforeFirstArg:
#   Enabled: true
#   AllowForAlignment: true

# Layout/SpaceInLambdaLiteral:
#   Enabled: true
#   EnforcedStyle: require_no_space

# Lint/EmptyWhen:
#   Enabled: true
#   AllowComments: true

# Lint/MissingCopEnableDirective:
#   Enabled: true
#   MaximumRangeSize: .inf

# Lint/PercentStringArray:
#   Enabled: true
#   Exclude:
#     - 'config/initializers/secure_headers.rb'

# Lint/SafeNavigationChain:
#   Enabled: true
#   AllowedMethods:
#     - present?
#     - blank?
#     - presence
#     - try
#     - try!

Lint/SafeNavigationConsistency:
  Enabled: true
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!

# Lint/ShadowedArgument:
#   Enabled: true
#   IgnoreImplicitReferences: false

# Lint/UnusedBlockArgument:
#   Enabled: true
#   AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false

# Lint/Void:
#   Enabled: true
#   CheckForMethodsWithNoSideEffects: false

Metrics/ModuleLength:
  CountComments: false
  Max: 200
  Description: Avoid modules longer than 100 lines of code.
  Enabled: true
  Exclude:
  - spec/**/*

Naming/BlockParameterName:
  Enabled: true
  MinNameLength: 1
  AllowNamesEndingInNumbers: true
  AllowedNames: []
  ForbiddenNames: []

# Naming/HeredocDelimiterCase:
#   Enabled: true
#   EnforcedStyle: uppercase

Naming/MethodParameterName:
  MinNameLength: 2

Naming/PredicateName:
  Enabled: true
  AllowedMethods:
    - is_a?
  ForbiddenPrefixes:
    # overriding to allow "has_"
    - is_
    - have_

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Naming/VariableNumber:
  AllowedIdentifiers: ial_1, ial_2, with_ial_1, with_ial_2, ready_to_activate_ial_2, ready_to_activate_ial_1

# Performance/CollectionLiteralInLoop:
#   Enabled: false

# Performance/DoubleStartEndWith:
#   Enabled: true
#   IncludeActiveSupportAliases: false

Performance/FlatMap:
  Enabled: true
  EnabledForFlattenWithoutParams: false

Performance/InefficientHashSearch:
  Enabled: true
  Safe: false

Performance/RangeInclude:
  Enabled: true
  Safe: false

# Performance/RedundantMerge:
#   Enabled: true
#   MaxKeyValuePairs: 2

# Rails/ApplicationMailer:
#   Enabled: false

Rails/Blank:
  Enabled: false

Rails/CompactBlank:
  Enabled: false

# Rails/Delegate:
#   Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rails/DotSeparatedKeys:
  Enabled: false

# Rails/DurationArithmetic:
#   Enabled: false

Rails/DuplicateScope:
  Enabled: false

Rails/DynamicFindBy:
  Exclude:
    - spec/features/**/*.rb

# # Disabling this can cause confusing errors and disabling it should be avoided
# Rails/Exit:
#   Enabled: true

# Rails/FilePath:
#   Enabled: false

Rails/HttpPositionalArguments:
  Description: Use keyword arguments instead of positional arguments in http method calls.
  Enabled: true
  Include:
    - spec/**/*
    - test/**/*

# Rails/I18nLazyLookup:
#   Enabled: false

Rails/I18nLocaleAssignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/IgnoredColumnsAssignment:
  Enabled: false

# Rails/NegateInclude:
#   Enabled: false

Rails/Output:
  Enabled: true
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - spec/**/*.rb # in addition to default

Rails/FindEach:
  # This generates too many false positives.
  # It's good advice for active record relations, but it assumes any use of an `#all` method
  # is an active record relation.
  Enabled: false

Rails/Pluck:
  # This generates false positives similar to Rails/FindEach
  Enabled: false

Rails/Present:
  Enabled: false

# Rails/RedundantPresenceValidationOnBelongsTo:
#   Enabled: false

# Rails/RelativeDateConstant:
#   Enabled: false

# Rails/ResponseParsedBody:
#   Enabled: false

# Rails/RootPathnameMethods:
#   Enabled: false

# Rails/SkipsModelValidations:
#   Enabled: true
#   Exclude:
#     - 'spec/**/*.rb'

Rails/StripHeredoc:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/TimeZone:
  Description: Checks the correct usage of time zone aware methods.
  StyleGuide: https://github.com/bbatsov/rails-style-guide#time
  Enabled: true
  EnforcedStyle: strict
  SupportedStyles:
    - strict
    - flexible

# Rails/ToFormattedS:
#   Enabled: false

Rails/ToSWithArgument:
  Enabled: false

# Rails/WhereNot:
#   Enabled: false

# Rails/WhereRange:
#   Enabled: false

RSpec:
  Enabled: false

## This will require a manual spec update
# RSpec/ContextWording:
#   Prefixes:
#     - when
#     - with
#     - without

RSpec/ExpectChange:
  # A couple people expressed a preference for block
  EnforcedStyle: block
  Enabled: true

RSpecRails/HttpStatus:
  Enabled: true

RSpecRails/HaveHttpStatus:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

# Not enabled yet. Still testing.
RSpec/MultipleMemoizedHelpers:
  Enabled: false
  # at minimum, 7 is required for testing RBAC:
  #   4 user team roles
  #   1 "not on the team" role
  #   1 team
  #   1 object the permission is tested for
  Max: 7

RSpec/NotToNot:
  Enabled: true
  EnforcedStyle: to_not

RSpec/LeakyConstantDeclaration:
  Enabled: true

RSpec/MissingExpectationTargetMethod:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/RedundantPredicateMatcher:
  Enabled: true

RSpec/StringAsInstanceDoubleConstant:
  Enabled: true

# Security/JSONLoad:
#   AutoCorrect: false
#   Enabled: true
#   SafeAutoCorrect: false

Security/Open:
  Enabled: true
  Safe: false

Security/YAMLLoad:
  Enabled: true
  SafeAutoCorrect: false

# Style/ArgumentsForwarding:
#   Enabled: false

Style/AndOr:
  Description: Use &&/|| instead of and/or.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-and-or-or
  EnforcedStyle: conditionals
  SupportedStyles:
  - always
  - conditionals

# Style/BarePercentLiterals:
#   Enabled: true
#   EnforcedStyle: bare_percent

# Style/ClassCheck:
#   Enabled: true
#   EnforcedStyle: is_a?

# Style/CommandLiteral:
#   Enabled: true
#   EnforcedStyle: mixed
#   AllowInnerBackticks: false

# # Warn on empty else statements
# # empty - warn only on empty else
# # nil - warn on else with nil in it
# # both - warn on empty else and else with nil in it
# Style/EmptyElse:
#   EnforcedStyle: both
#   SupportedStyles:
#     - empty
#     - nil
#     - both

Style/EmptyMethod:
  Enabled: false

# Style/For:
#   Enabled: true
#   EnforcedStyle: each

Style/GlobalVars:
  Enabled: true
  AllowedVariables: []

# Style/IfUnlessModifier:
#   Description: Favor modifier if/unless usage when you have a single-line body.
#   StyleGuide: https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier
#   Enabled: true

# Style/LambdaCall:
#   Enabled: true
#   EnforcedStyle: call

Style/LineEndConcatenation:
  Enabled: true
  SafeAutoCorrect: false

# Style/MixinGrouping:
#   Enabled: true
#   EnforcedStyle: separated

# Style/MultilineMemoization:
#   Enabled: true
#   EnforcedStyle: keyword

# Style/NilComparison:
#   Enabled: true
#   EnforcedStyle: predicate

# Style/NonNilCheck:
#   Enabled: true
#   IncludeSemanticChanges: false

# Style/NumericLiteralPrefix:
#   Enabled: true
#   EnforcedOctalStyle: zero_with_o

# Style/PercentLiteralDelimiters:
#   # Specify the default preferred delimiter for all types with the 'default' key
#   # Override individual delimiters (even with default specified) by specifying
#   # an individual key
#   PreferredDelimiters:
#     default: ()
#     '%i': '[]'
#     '%I': '[]'
#     '%r': '{}'
#     '%w': '[]'
#     '%W': '[]'

# Style/SafeNavigation:
#   Enabled: true
#   ConvertCodeThatCanStartToReturnNil: false
#   AllowedMethods:
#     - present?
#     - blank?
#     - presence
#     - try
#     - try!

# Style/Semicolon:
#   Enabled: true
#   AllowAsExpressionSeparator: false

# Style/StringLiterals:
#   Description: Checks if uses of quotes match the configured preference.
#   StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
#   EnforcedStyle: single_quotes
#   SupportedStyles:
#   - single_quotes
#   - double_quotes
#   ConsistentQuotesInMultiline: true

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInArrayLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last item of all
  # non-empty array and hash literals.
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInHashLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last item of all
  # non-empty array and hash literals.
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/WordArray:
  MinSize: 3

Style/YodaCondition:
  Enabled: true
  EnforcedStyle: forbid_for_all_comparison_operators

Style/SymbolArray:
  MinSize: 3

Metrics:
  Enabled: true

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

RSpec/ExampleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
  EnforcedStyle: with_fixed_indentation

Layout/LineEndStringConcatenationIndentation:
  # Disabled because we don't yet agree on an enforced style
  Enabled: false
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  # We like `.to change { Model.count }`
  Exclude:
    - spec/**/*.rb

Rails/RequestReferer:
  Enabled: false
