language: ruby
before_script:
- bundle exec rake db:setup
rvm:
- 2.3.3
cache: bundler
script:
  - make test
  - bundle exec codeclimate-test-reporter
addons:
  postgresql: "9.3"
services:
  - postgresql
env:
  - RACK_ENV=test
  - RAILS_ENV=test
addons:
  code_climate:
    repo_token:
      secure: "GCGAeg6FdflZxjN711mmAH45BWdYaKImASjiu19FDS+BWaQMG4cmwPMfziUNxI3kDMIp+Ox1H4sCZ/zruHVDRKbP8TdQ9eX1Bvll+Z5QIKwPIKEwL1s/eX1C9+MZIeKS609NsEbxPd8yZZee3NDkJ5N9eHp7mGZaa9jgz7WDjjBag4jnPofe41boZEr2E1zudaQ3nTrWejG/6sJclBNJ0LaiY0no1usgTyAjFnNgSgM19p/DPOSA9Jp6alIkauLcYFZHg3lLVEfTMZiUS6JGfMVoFNNrdobgmNmYWYId91Lw9Yy47ptLCHMjBrtpWoEE8M/flgA0EpxmXcXvPpVy78Hnmt5oVAyasKaX+SjG110sm3gQWDTJFmWYxfAsKv0VPV++v4VhvLgOtrdmxuf4MBf9NBEVR1asGhemR0i5ImLvjj/jNN4I02qfvyNlUwoBDQBzmzK2erHEhdjwWz6hBQ9CYZv/xoX4mKOoAcJPlbCcCgs800ZKBf1txSrF3H4TTV5S2gUy9ZFwncl/Ykhnn7deRs9CVOR/qiy2uK3sP80QQy5A2zza8ooBwT9EzFwIVMFSkMKS4szKKrfUzhQWaU7rEEg+9Fgx+2ZYsD0NxsNjZDCVDk4OBy1q+koyX3KhSKXOAx+Xbt8vvb0CaEiL5sIrXuAksnUfZ7kjG/MUYeo="
