# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Wicked::Wizard`.
# Please instead update this file by running `bin/tapioca dsl Wicked::Wizard`.


module Wicked::Wizard
  mixes_in_class_methods ::Wicked::Controller::Concerns::Steps::ClassMethods
end
