#!/bin/bash

# This script is called by identity-devops cookbooks as part of the deployment
# process. It runs build steps needed to complete building the application,
# such as vendoring ruby/nodejs libraries and compiling static assets.

set -euo pipefail

echo "deploy/build starting"
echo "HOME: ${HOME-}"
cd "$(dirname "$0")/.."

set -x

# default bundle directory to shared directory
: ${BUNDLE_DIR=/srv/dashboard/shared/bundle}

# use system libxml2, not the one vendored with nokogiri
bundle config build.nokogiri --use-system-libraries
bundle config set --local deployment 'true'
bundle config set --local path $BUNDLE_DIR
bundle config set --local without 'deploy development test'

bundle install --jobs 4
npm ci --omit=dev --cache .npm-cache
bundle exec rake assets:precompile

set +x

echo "deploy/build finished"
