[secrets]
  description = 'secrets custom overrides for identity-dashboard'
  [[secrets.passthrough]]
    type = "file"
    target = "gitleaks.toml"
    value = '.gitleaks.toml'
  # this rule is not as good as gitleaks's default RSA key rule and causes false positives
  # it only checks the "RSA PRIVATE KEY" header and not the contents of the key
  # we check key contents via stopwords
  [[secrets.ruleset]]
    disable = true
    [secrets.ruleset.identifier]
      type  = "gitleaks_rule_id"
      value = "RSA private key"