20:
  fullname: Library of Congress
  name: LOC
  branch: Legislative
  url: loc.gov
23:
  fullname: Judicial Branch
  name: Judicial
  branch: Judicial
  url:
11:
  fullname: Department of Agriculture
  name: USDA
  branch: Executive
  url: usda.gov
24:
  fullname: Department of Commerce
  name: DOC
  branch: Executive
  url: commerce.gov
8:
  fullname: Department of Defense
  name: DOD
  branch: Executive
  url: defense.gov
25:
  fullname: Department of Education
  name: ED
  branch: Executive
  url: ed.gov
10:
  fullname: Department of Energy
  name: DOE
  branch: Executive
  url: energy.gov
26:
  fullname: Department of Justice
  name: DOJ
  branch: Executive
  url: justice.gov
19:
  fullname: Department of Health and Human Services
  name: HHS
  branch: Executive
  url: hhs.gov
1:
  fullname: Department of Homeland Security
  name: DHS
  branch: Executive
  url: dhs.gov
12:
  fullname: Department of Housing and Urban Development
  name: HUD
  branch: Executive
  url: hud.gov
16:
  fullname: Department of the Interior
  name: DOI
  branch: Executive
  url: doi.gov
14:
  fullname: Department of Labor
  name: DOL
  branch: Executive
  url: dol.gov
27:
  fullname: Department of State
  name: DOS
  branch: Executive
  url: state.gov
6:
  fullname: Department of Transportation
  name: DOT
  branch: Executive
  url: transportation.gov
28:
  fullname: Department of the Treasury
  name: TREAS
  branch: Executive
  url: treasury.gov
29:
  fullname: Department of Veterans Affairs
  name: VA
  branch: Executive
  url: va.gov
30:
  fullname: Administrative Conference of the United States
  name: ACUS
  branch: Independent
  url: acus.gov
31:
  fullname: AbilityOne Commission
  name: ABILITYONE
  branch: Independent
  url: abilityone.gov
32:
  fullname: Access Board
  name: USAB
  branch: Independent
  url: access-board.gov
33:
  fullname: Advisory Council on Historic Preservation
  name: ACHP
  branch: Independent
  url: achp.gov
34:
  fullname: African Development Foundation
  name: USADF
  branch: Independent
  url: usadf.gov
35:
  fullname: American Battle Monuments Commission
  name: ABMC
  branch: Independent
  url: abmc.gov
36:
  fullname: Appalachian Regional Commission
  name: ARC
  branch: Independent
  url: arc.gov
37:
  fullname: Armed Forces Retirement Home
  name: AFRH
  branch: Independent
  url: afrh.gov
38:
  fullname: Barry Goldwater Scholarship and Excellence in Education Foundation
  name: GOLDWATER
  branch: Independent
  url: goldwaterscholarship.gov
39:
  fullname: Central Intelligence Agency
  name: CIA
  branch: Independent
  url: cia.gov
40:
  fullname: Chemical Safety Board
  name: CSB
  branch: Independent
  url: csb.gov
41:
  fullname: Christopher Columbus Fellowship Foundation
  name: CCFF
  branch: Independent
  url: columbusfellowshipfoundation.org
42:
  fullname: Commission for the Preservation of America's Heritage Abroad
  name: HERITAGEABROAD
  branch: Independent
  url: heritageabroad.gov
43:
  fullname: Commission of Fine Arts
  name: CFA
  branch: Independent
  url: cfa.gov
44:
  fullname: Commission on Civil Rights
  name: USCCR
  branch: Independent
  url: usccr.gov
45:
  fullname: Commodity Futures Trading Commission
  name: CFTC
  branch: Independent
  url: cftc.gov
46:
  fullname: Consumer Financial Protection Bureau
  name: CFPB
  branch: Independent
  url: consumerfinance.gov
47:
  fullname: Consumer Product Safety Commission
  name: CPSC
  branch: Independent
  url: cpsc.gov
48:
  fullname: Corporation for National & Community Service
  name: CNCS
  branch: Independent
  url: nationalservice.gov
49:
  fullname: Corporation for Public Broadcasting
  name: CPB
  branch: Independent
  url: cpb.org
50:
  fullname: Council of Inspectors General on Integrity and Efficiency
  name: CIGIE
  branch: Independent
  url: cigie.gov
51:
  fullname: Court Services and Offender Supervision
  name: CSOSA
  branch: Independent
  url: csosa.gov
52:
  fullname: Defense Nuclear Facilities Safety Board
  name: DNFSB
  branch: Independent
  url: dnfsb.gov
53:
  fullname: Delta Regional Authority
  name: DRA
  branch: Independent
  url: dra.gov
54:
  fullname: Denali Commission
  name: DENALI
  branch: Independent
  url: denali.gov
55:
  fullname: Director of National Intelligence
  name: DNI
  branch: Independent
  url: dni.gov
56:
  fullname: District of Columbia Courts
  name: DC COURTS
  branch: Independent
  url: dccourts.gov
57:
  fullname: Dwight D. Eisenhower Memorial Commission
  name: DDEMC
  branch: Independent
  url: eisenhowermemorial.gov
58:
  fullname: Election Assistance Commission
  name: EAC
  branch: Independent
  url: eac.gov
59:
  fullname: Environmental Protection Agency
  name: EPA
  branch: Independent
  url: epa.gov
60:
  fullname: Equal Employment Opportunity Commission
  name: EEOC
  branch: Independent
  url: eeoc.gov
3:
  fullname: Executive Office of the President
  name: EOP
  branch: Independent
  url: whitehouse.gov
61:
  fullname: Export/Import Bank of the U.S.
  name: EXIM
  branch: Independent
  url: exim.gov
62:
  fullname: Farm Credit Administration
  name: FCA
  branch: Independent
  url: fca.gov
63:
  fullname: Farm Credit System Insurance Corporation
  name: FCSIC
  branch: Independent
  url: fcisc.gov
64:
  fullname: Federal Communications Commission
  name: FCC
  branch: Independent
  url: broadband.gov
65:
  fullname: Federal Deposit Insurance Corporation
  name: FDIC
  branch: Independent
  url: fdic.gov
66:
  fullname: Federal Election Commission
  name: FEC
  branch: Independent
  url: fec.gov
67:
  fullname: Federal Energy Regulatory Commission
  name: FERC
  branch: Independent
  url: ferc.gov
68:
  fullname: Federal Financial Institutions Examination Council
  name: FFIEC
  branch: Independent
  url: ffiec.gov
69:
  fullname: Federal Home Loan Bank System
  name: FHLBS
  branch: Independent
  url: fhlbanks.com
70:
  fullname: Federal Home Loan Mortgage Corporation
  name: FHALMC
  branch: Independent
  url: freddiemac.com
71:
  fullname: Federal Housing Finance Agency
  name: FHFA
  branch: Independent
  url: fhfa.gov
72:
  fullname: Federal Labor Relations Authority
  name: FLRA
  branch: Independent
  url: flra.gov
73:
  fullname: Federal Maritime Commission
  name: FMC
  branch: Independent
  url: fmc.gov
74:
  fullname: Federal Mediation and Conciliation Service
  name: FMCS
  branch: Independent
  url: adr.gov
75:
  fullname: Federal Mine Safety and Health Review Commission
  name: FMSHRC
  branch: Independent
  url: fmshrc.gov
76:
  fullname: Federal National Mortgage Association
  name: FNMA
  branch: Independent
  url: fanniemae.com
77:
  fullname: Federal Reserve Board of Governors
  name: FRBG
  branch: Independent
  url: federalreserve.gov
78:
  fullname: Federal Retirement Thrift Investment Board
  name: FRTIB
  branch: Independent
  url: tsp.gov
79:
  fullname: Federal Trade Commission
  name: FTC
  branch: Independent
  url: ftc.gov
9:
  fullname: General Services Administration
  name: GSA
  branch: Independent
  url: gsa.gov
80:
  fullname: Government Accountability Office
  name: GAO
  branch: Independent
  url: gao.gov
81:
  fullname: Government of the District of Columbia
  name: GDC
  branch: Independent
  url: dc.gov
82:
  fullname: Gulf Coast Ecosystem Restoration Council
  name: GCERC
  branch: Independent
  url: restorethegulf.gov
83:
  fullname: Harry S. Truman Scholarship Foundation
  name: TRUMAN
  branch: Independent
  url: truman.gov
84:
  fullname: Institute of American Indian and Alaska Native Culture and Arts Development
  name: IAIA
  branch: Independent
  url: iaia.edu
85:
  fullname: Institute of Museum and Library Services
  name: IMLS
  branch: Independent
  url: imls.gov
86:
  fullname: Inter-American Foundation
  name: IAF
  branch: Independent
  url: iaf.gov
120:
  fullname: International Development Finance Corporation
  name: DFC
  branch: Independent
  url: dfc.gov
87:
  fullname: International Trade Commission
  name: USITC
  branch: Independent
  url: usitc.gov
88:
  fullname: James Madison Memorial Fellowship Foundation
  name: MADISON
  branch: Independent
  url: jamesmadison.gov
89:
  fullname: Japan-United States Friendship Commission
  name: JUSFC
  branch: Independent
  url: jusfc.gov
90:
  fullname: John F. Kennedy Center for the Performing Arts
  name: KENNEDY CENTER
  branch: Independent
  url: kennedy-center.org
91:
  fullname: Legal Services Corporation
  name: LSC
  branch: Independent
  url: lsc.gov
92:
  fullname: Marine Mammal Commission
  name: MMC
  branch: Independent
  url: mmc.gov
93:
  fullname: Merit Systems Protection Board
  name: MSPB
  branch: Independent
  url: mspb.gov
94:
  fullname: Millennium Challenge Corporation
  name: MCC
  branch: Independent
  url: mcc.gov
95:
  fullname: Morris K. Udall and Stewart L. Udall Foundation
  name: UDALL
  branch: Independent
  url: ecr.gov
96:
  fullname: National Aeronautics and Space Administration
  name: NASA
  branch: Independent
  url: nasa.gov
97:
  fullname: National Archives and Records Administration
  name: NARA
  branch: Independent
  url: archives.gov
98:
  fullname: National Capital Planning Commission
  name: NCPC
  branch: Independent
  url: ncpc.gov
99:
  fullname: National Council on Disability
  name: NCD
  branch: Independent
  url: ncd.gov
100:
  fullname: National Credit Union Administration
  name: NCUA
  branch: Independent
  url: mycreditunion.gov
101:
  fullname: National Endowment for the Arts
  name: NEA
  branch: Independent
  url: arts.gov
102:
  fullname: National Endowment for the Humanities
  name: NEH
  branch: Independent
  url: edsitement.neh.gov
103:
  fullname: National Gallery of Art
  name: National Gallery of Art
  branch: Independent
  url: nga.gov
5:
  fullname: National Geospatial-Intelligency Agency
  name: NGA
  branch: Independent
  url: nga.mil
18:
  fullname: National Labor Relations Board
  name: NLRB
  branch: Independent
  url: nlrb.gov
104:
  fullname: National Mediation Board
  name: NMB
  branch: Independent
  url: nmb.gov
105:
  fullname: National Nanotechnology Coordination Office
  name: NNCO
  branch: Independent
  url: nano.gov
106:
  fullname: National Nuclear Security Administration
  name: NNSA
  branch: Independent
  url: nnss.gov
107:
  fullname: National Science Foundation
  name: NSF
  branch: Independent
  url: nsf.gov
108:
  fullname: National Security Agency
  name: NSA
  branch: Independent
  url: intelligencecareers.gov
109:
  fullname: National Security Commission on Artificial Intelligence
  name: NSCAI
  branch: Independent
  url: nscai.gov
110:
  fullname: National Transportation Safety Board
  name: NTSB
  branch: Independent
  url: ntsb.gov
111:
  fullname: Networking Information Technology Research and Development
  name: ITRD
  branch: Independent
  url: itrd.gov
112:
  fullname: Northern Border Regional Commission
  name: NBRC
  branch: Independent
  url: nbrc.gov
113:
  fullname: Nuclear Regulatory Commission
  name: NRC
  branch: Independent
  url: nrc.gov
114:
  fullname: Nuclear Waste Technical Review Board
  name: NWTRB
  branch: Independent
  url: nwtrb.gov
115:
  fullname: Occupational Safety & Health Review Commission
  name: OSHRC
  branch: Independent
  url: oshrc.gov
116:
  fullname: Office of Government Ethics
  name: OGE
  branch: Independent
  url: oge.gov
117:
  fullname: Office of Navajo and Hopi Indian Relocation
  name: ONHR
  branch: Independent
  url:
2:
  fullname: Office of Personnel Management
  name: OPM
  branch: Independent
  url: usajobs.gov
118:
  fullname: Office of Special Counsel
  name: OSC
  branch: Independent
  url: osc.gov
119:
  fullname: Office of the Federal Coordinator for Alaska Natural Gas Transportation Projects
  name: OFCANGTP
  branch: Independent
  url:
121:
  fullname: Patient-Centered Outcomes Research Trust Fund
  name: PCORTF
  branch: Independent
  url:
122:
  fullname: Peace Corps
  name: PC
  branch: Independent
  url: peacecorps.gov
123:
  fullname: Pension Benefit Guaranty Corporation
  name: PBGC
  branch: Independent
  url: pbgc.gov
124:
  fullname: Postal Regulatory Commission
  name: PRC
  branch: Independent
  url: prc.gov
125:
  fullname: Postal Service
  name: USPS
  branch: Independent
  url: usps.com
126:
  fullname: Presidio Trust
  name: Presidio Trust
  branch: Independent
  url: presidio.gov
127:
  fullname: Privacy and Civil Liberties Oversight Board
  name: PCLOB
  branch: Independent
  url: pclob.gov
128:
  fullname: Public Buildings Reform Board
  name: PBRB
  branch: Independent
  url: pbrb.gov
129:
  fullname: Public Company Accounting Oversight Board
  name: PCAOB
  branch: Independent
  url: pcaobus.org
130:
  fullname: Public Defender Service for the District of Columbia
  name: PDSDC
  branch: Independent
  url: pdsdc.org
4:
  fullname: Railroad Retirement Board
  name: RRB
  branch: Independent
  url: rrb.gov
13:
  fullname: Securities and Exchange Commission
  name: SEC
  branch: Independent
  url: sec.gov
131:
  fullname: Securities Investor Protection Corporation
  name: SIPC
  branch: Independent
  url: sipc.org
132:
  fullname: Selective Service System
  name: SSS
  branch: Independent
  url: sss.gov
17:
  fullname: Small Business Administration
  name: SBA
  branch: Independent
  url: sba.gov
133:
  fullname: Smithsonian Institution
  name: SI
  branch: Independent
  url: si.edu
134:
  fullname: Social Security Administration
  name: SSA
  branch: Independent
  url: ssa.gov
135:
  fullname: Social Security Advisory Board
  name: SSAB
  branch: Independent
  url: ssab.gov
136:
  fullname: State Justice Institute
  name: SJI
  branch: Independent
  url: sji.gov
137:
  fullname: Surface Transportation Board
  name: STB
  branch: Independent
  url: stb.gov
138:
  fullname: Tennessee Valley Authority
  name: TVA
  branch: Independent
  url: tva.gov
139:
  fullname: Trade and Development Agency
  name: USTDA
  branch: Independent
  url: ustda.gov
140:
  fullname: U.S. Agency for Global Media
  name: USAGM
  branch: Independent
  url: usagm.gov
15:
  fullname: U.S. Agency for International Development
  name: USAID
  branch: Independent
  url: usaid.gov
142:
  fullname: U.S. Army Corps of Engineers
  name: USACE
  branch: Independent
  url: usace.army.mil
143:
  fullname: United Mine Workers of America Benefit Funds
  name: UMWABF
  branch: Independent
  url: umwafunds.org
144:
  fullname: United States Court of Appeals for Veterans Claims
  name: CAVC
  branch: Independent
  url: uscourts.cavc.gov
145:
  fullname: United States Holocaust Memorial Museum
  name: USHMM
  branch: Independent
  url: ushmm.gov
146:
  fullname: United States Institute of Peace
  name: USIP
  branch: Independent
  url: usip.gov
147:
  fullname: United States Interagency Council on Homelessness
  name: USICH
  branch: Independent
  url: ich.gov
149:
  fullname: Vietnam Education Foundation
  name: VEF
  branch: Independent
  url: vef.gov
149:
  fullname: Internal Revenue Service
  name: IRS
  branch: Independent
  url: irs.gov
21:
  name: 'State, local governments or tribes'