development: &default
  adapter: postgresql
  database: identity-dashboard_development
  encoding: utf8
  min_messages: warning
  pool: <%= IdentityConfig.store.db_pool %>
  reaping_frequency: <%= IdentityConfig.store.dp_reaping_frequency %>
  timeout: 5000
  host: localhost

test:
    <<: *defaults
    adapter: postgresql
    pool: 10
    checkout_timeout: 10
    database: <%= ENV['POSTGRES_DB'] || "identity_idp_test#{ENV['TEST_ENV_NUMBER']}" %>
    user: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['DOCKER_DB_HOST'] || 'localhost' %>
# This whole file is overwritten by chef in production.
#production:
