development: &default
  adapter: postgresql
  database: identity-dashboard_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(Figaro.env.db_pool || 5) %>
  reaping_frequency: <%= Integer(Figaro.env.dp_reaping_frequency || 10) %>
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: identity-dashboard_test

# This whole file is overwritten by chef in production.
#production:
