development: &default
  adapter: postgresql
  database: identity-dashboard_development
  encoding: utf8
  min_messages: warning
  pool: <%= IdentityConfig.store.db_pool %>
  reaping_frequency: <%= IdentityConfig.store.dp_reaping_frequency %>
  timeout: 5000
  host: localhost

test:
  host: <%= ENV['DOCKER_DB_HOST'] || 'localhost' %>
  <<: *default
  database: identity-dashboard_test

# This whole file is overwritten by chef in production.
#production:
