development: &default
  adapter: postgresql
  database: identity-dashboard_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(Figaro.env.DB_POOL || 5) %>
  reaping_frequency: <%= Integer(Figaro.env.DP_REAPING_FREQUENCY || 10) %>
  timeout: 5000

test:
  <<: *default
  database: identity-dashboard_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(Figaro.env.MAX_THREADS || 5), Integer(Figaro.env.DB_POOL || 5)].max %>
  timeout: 5000
  url:  <%= Figaro.env.DATABASE_URL %>

staging: *deploy
