default: &default
  secret_key_base: MGhvYnpIWnJaRHhLaDJrRkpOd1JqWFhHUHMuRFpVeGRhRE5GVHY1NDdBQkwxM0NkWGdnY1NnZmhNMWhCRzBBRG80U2YuTG5hMURrb3NkZ2VURkJOelZkZmhFMUM0TWJwdGFwcFJhM21hRHdQVTFoRUpWZXZCbmp3YnROZkZ0a2MK

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  secret_key_base: <%= ENV['DASHBOARD_SECRET_KEY_BASE'] %>
