default: &default
  # Just use the secret_key_base set in application.yml or environ.
  # Devise expects to load it from here using
  # Rails.application.secrets.secret_key_base.
  secret_key_base: "<%= Figaro.env.secret_key_base! %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
