default: &default
  secret_key_base: MGhvYnpIWnJaRHhLaDJrRkpOd1JqWFhHUHMuRFpVeGRhRE5GVHY1NDdBQkwxM0NkWGdnY1NnZmhNMWhCRzBBRG80U2YuTG5hMURrb3NkZ2VURkJOelZkZmhFMUM0TWJwdGFwcFJhM21hRHdQVTFoRUpWZXZCbmp3YnROZkZ0a2MK
  http_auth_username: <%= ENV["SP_NAME"] %>
  http_auth_password: <%= ENV["SP_PASS"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
