deploys:

  # Production
  - app: 'identity-idp'
    env: 'prod'
    host: 'https://secure.login.gov'

  # Staging
  - app: 'identity-idp'
    env: 'staging'
    host: 'https://idp.staging.login.gov'

  # Agency integration
  - app: 'identity-idp'
    env: 'int'
    host: 'https://idp.int.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'int'
    host: 'https://dashboard.int.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'int'
    host: 'https://int-identity-oidc-sinatra.app.cloud.gov'
  - app: 'identity-saml-rails'
    env: 'int'
    host: 'https://sp-rails.int.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'int'
    host: 'https://int-identity-saml-sinatra.app.cloud.gov'

  # Quality assurance
  - app: 'identity-idp'
    env: 'qa'
    host: 'https://idp.qa.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'qa'
    host: 'https://dashboard.qa.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'qa'
    host: 'https://qa-identity-oidc-sinatra.app.cloud.gov'
  - app: 'identity-saml-rails'
    env: 'qa'
    host: 'https://sp-rails.qa.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'qa'
    host: 'https://qa-identity-saml-sinatra.app.cloud.gov'

  # Development
  - app: 'identity-idp'
    env: 'dev'
    host: 'https://idp.dev.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'dev'
    host: 'https://dashboard.dev.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'dev'
    host: 'https://dev-identity-oidc-sinatra.app.cloud.gov'
  - app: 'identity-saml-rails'
    env: 'dev'
    host: 'https://sp-rails.dev.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'dev'
    host: 'https://dev-identity-saml-sinatra.app.cloud.gov'
