deploys:

  # Production
  - app: 'identity-idp'
    env: 'prod'
    host: 'https://secure.login.gov'
  - app: 'identity-oidc-sinatra'
    env: 'prod'
    host: 'https://prod-identity-oidc-sinatra.app.cloud.gov/'
  - app: 'identity-saml-sinatra'
    env: 'prod'
    host: 'https://prod-identity-saml-sinatra.app.cloud.gov/'
  - app: 'identity-pki'
    env: 'prod'
    host: 'https://checking-deploy.pivcac.prod.login.gov'

  # Staging
  - app: 'identity-idp'
    env: 'staging'
    host: 'https://idp.staging.login.gov'
  - app: 'identity-oidc-sinatra'
    env: 'staging'
    host: 'https://staging-identity-oidc-sinatra.app.cloud.gov/'
  - app: 'identity-saml-sinatra'
    env: 'staging'
    host: 'https://staging-identity-saml-sinatra.app.cloud.gov/'
  - app: 'identity-pki'
    env: 'staging'
    host: 'https://checking-deploy.pivcac.staging.login.gov'

  # Data Migration
  - app: 'identity-idp'
    env: 'dm'
    host: 'https://idp.dm.login.gov'
  - app: 'identity-oidc-sinatra'
    env: 'dm'
    host: 'https://dm-identity-oidc-sinatra.app.cloud.gov/'
  - app: 'identity-saml-sinatra'
    env: 'dm'
    host: 'https://dm-identity-saml-sinatra.app.cloud.gov/'
  - app: 'identity-pki'
    env: 'dm'
    host: 'https://checking-deploy.pivcac.dm.login.gov'

  # Agency integration
  - app: 'identity-idp'
    env: 'int'
    host: 'https://idp.int.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'int'
    host: 'https://dashboard.int.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'int'
    host: 'https://int-identity-oidc-sinatra.app.cloud.gov/'
  - app: 'identity-saml-sinatra'
    env: 'int'
    host: 'https://int-identity-saml-sinatra.app.cloud.gov/'
  - app: 'identity-pki'
    env: 'int'
    host: 'https://checking-deploy.pivcac.int.identitysandbox.gov'

  # Development
  - app: 'identity-idp'
    env: 'dev'
    host: 'https://idp.dev.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'dev'
    host: 'https://dashboard.dev.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'dev'
    host: 'https://dev-identity-oidc-sinatra.app.cloud.gov/'
  - app: 'identity-saml-sinatra'
    env: 'dev'
    host: 'https://dev-identity-saml-sinatra.app.cloud.gov/'
  - app: 'identity-pki'
    env: 'dev'
    host: 'https://checking-deploy.pivcac.dev.identitysandbox.gov'
