deploys:

  # Production
  - app: 'identity-idp'
    env: 'prod'
    host: 'https://secure.login.gov'

  # Staging
  - app: 'identity-idp'
    env: 'staging'
    host: 'https://idp.staging.login.gov'

  # Agency integration
  - app: 'identity-idp'
    env: 'int'
    host: 'https://idp.int.identitysandbox.gov'
  - app: 'identity-sp-rails'
    env: 'int'
    host: 'https://sp.int.identitysandbox.gov'
  - app: 'identity-sp-sinatra'
    env: 'int'
    host: 'https://sp-sinatra.int.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'int'
    host: 'https://dashboard.int.identitysandbox.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'int'
    host: 'https://sp-oidc-sinatra.int.identitysandbox.gov/'

  # Quality assurance
  - app: 'identity-idp'
    env: 'qa'
    host: 'https://idp.qa.identitysandbox.gov'
  - app: 'identity-sp-rails'
    env: 'qa'
    host: 'https://sp.qa.identitysandbox.gov'
  - app: 'identity-sp-sinatra'
    env: 'qa'
    host: 'https://sp-sinatra.qa.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'qa'
    host: 'https://dashboard.qa.identitysandbox.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'qa'
    host: 'https://sp-oidc-sinatra.qa.identitysandbox.gov/'

  # Development
  - app: 'identity-idp'
    env: 'dev'
    host: 'https://idp.dev.identitysandbox.gov'
  - app: 'identity-sp-rails'
    env: 'dev'
    host: 'https://sp.dev.identitysandbox.gov'
  - app: 'identity-sp-sinatra'
    env: 'dev'
    host: 'https://sp-sinatra.dev.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'dev'
    host: 'https://dashboard.dev.identitysandbox.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'dev'
    host: 'https://sp-oidc-sinatra.dev.identitysandbox.gov/'
