deploys:

  # Production
  - app: 'identity-idp'
    env: 'prod'
    host: 'https://secure.login.gov'

  # Staging
  - app: 'identity-idp'
    env: 'staging'
    host: 'https://idp.staging.login.gov'

  # Agency integration
  - app: 'identity-idp'
    env: 'int'
    host: 'https://idp.int.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'int'
    host: 'https://dashboard.int.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'int'
    host: 'https://oidc-sinatra.int.identitysandbox.gov'
  - app: 'identity-saml-rails'
    env: 'int'
    host: 'https://saml-rails.int.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'int'
    host: 'https://saml-sinatra.int.identitysandbox.gov'

  # Quality assurance
  - app: 'identity-idp'
    env: 'qa'
    host: 'https://idp.qa.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'qa'
    host: 'https://dashboard.qa.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'qa'
    host: 'https://oidc-sinatra.qa.identitysandbox.gov'
  - app: 'identity-saml-rails'
    env: 'qa'
    host: 'https://saml-rails.qa.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'qa'
    host: 'https://saml-sinatra.qa.identitysandbox.gov'

  # Development
  - app: 'identity-idp'
    env: 'dev'
    host: 'https://idp.dev.identitysandbox.gov'
  - app: 'identity-dashboard'
    env: 'dev'
    host: 'https://dashboard.dev.identitysandbox.gov'
  - app: 'identity-oidc-sinatra'
    env: 'dev'
    host: 'https://oidc-sinatra.dev.identitysandbox.gov'
  - app: 'identity-saml-rails'
    env: 'dev'
    host: 'https://saml-rails.dev.identitysandbox.gov'
  - app: 'identity-saml-sinatra'
    env: 'dev'
    host: 'https://saml-sinatra.dev.identitysandbox.gov'
