deploys:
  - app: 'identity-idp'
    env: 'prod'
    host: 'https://secure.login.gov'
  - app: 'identity-sp-rails'
    env: 'prod'
  - app: 'identity-sp-sinatra'
    env: 'prod'
  - app: 'identity-dashboard'
    env: 'prod'
  - app: 'identity-openidconnect-sinatra'
    env: 'prod'

  - app: 'identity-idp'
    env: 'staging'
    host: 'https://idp.staging.login.gov'
  - app: 'identity-sp-rails'
    env: 'staging'
  - app: 'identity-sp-sinatra'
    env: 'staging'
  - app: 'identity-dashboard'
    env: 'staging'
  - app: 'identity-openidconnect-sinatra'
    env: 'staging'

  - app: 'identity-idp'
    env: 'pt'
    host: 'https://idp.pt.login.gov'
  - app: 'identity-sp-rails'
    env: 'pt'
    host: 'https://sp.pt.login.gov'
  - app: 'identity-sp-sinatra'
    env: 'pt'
    host: 'https://sp-sinatra.pt.login.gov'
  - app: 'identity-dashboard'
    env: 'pt'
    host: 'https://dashboard.pt.login.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'pt'
    host: 'https://sp-oidc-sinatra.pt.login.gov/'

  - app: 'identity-idp'
    env: 'int'
    host: 'https://idp.int.login.gov'
  - app: 'identity-sp-rails'
    env: 'int'
    host: 'https://sp.int.login.gov'
  - app: 'identity-sp-sinatra'
    env: 'int'
    host: 'https://sp-sinatra.int.login.gov'
  - app: 'identity-dashboard'
    env: 'int'
    host: 'https://dashboard.int.login.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'int'
    host: 'https://sp-oidc-sinatra.int.login.gov/'

  - app: 'identity-idp'
    env: 'qa'
    host: 'https://idp.qa.login.gov'
  - app: 'identity-sp-rails'
    env: 'qa'
    host: 'https://sp.qa.login.gov'
  - app: 'identity-sp-sinatra'
    env: 'qa'
    host: 'https://sp-sinatra.qa.login.gov'
  - app: 'identity-dashboard'
    env: 'qa'
    host: 'https://dashboard.qa.login.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'qa'
    host: 'https://sp-oidc-sinatra.qa.login.gov/'

  - app: 'identity-idp'
    env: 'dev'
    host: 'https://idp.dev.login.gov'
  - app: 'identity-sp-rails'
    env: 'dev'
    host: 'https://sp.dev.login.gov'
  - app: 'identity-sp-sinatra'
    env: 'dev'
    host: 'https://sp-sinatra.dev.login.gov'
  - app: 'identity-dashboard'
    env: 'dev'
    host: 'https://dashboard.dev.login.gov'
  - app: 'identity-openidconnect-sinatra'
    env: 'dev'
    host: 'https://sp-oidc-sinatra.dev.login.gov/'
