# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Browser::Middleware::Context`.
# Please instead update this file by running `bin/tapioca dsl Browser::Middleware::Context`.


class Browser::Middleware::Context
  include GeneratedUrlHelpersModule
  extend GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
  extend GeneratedPathHelpersModule
end
