# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionDispatch::IntegrationTest`.
# Please instead update this file by running `bin/tapioca dsl ActionDispatch::IntegrationTest`.


class ActionDispatch::IntegrationTest
  include GeneratedUrlHelpersModule
  extend GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
  extend GeneratedPathHelpersModule
end
