# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Devise::FailureApp`.
# Please instead update this file by running `bin/tapioca dsl Devise::FailureApp`.


class Devise::FailureApp
  include GeneratedUrlHelpersModule
  extend GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
  extend GeneratedPathHelpersModule
end
