# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::Redirecting`.
# Please instead update this file by running `bin/tapioca dsl ActionController::Redirecting`.


module ActionController::Redirecting
  mixes_in_class_methods ::AbstractController::UrlFor::ClassMethods
end
