# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::UrlFor`.
# Please instead update this file by running `bin/tapioca dsl ActionController::UrlFor`.


module ActionController::UrlFor
  mixes_in_class_methods ::AbstractController::UrlFor::ClassMethods
end
